import type { LocalizedText, PsychologyConcept } from './types';

const t = (nl: string, en: string): LocalizedText => ({ nl, en });

const sixCoreSources = ['acbs-six-core', 'acbs-act-model'];
const modelSources = ['acbs-act-model'];
const philosophySources = ['acbs-philosophical-roots', 'acbs-act-model'];

/**
 * Originele, tweetalige begrippencatalogus voor de ACT-theorielessen.
 * Broncontrole betekent hier alleen dat de plaats van het begrip in het ACT-model is nagegaan.
 */
export const actConcepts: PsychologyConcept[] = [
  {
    id: 'act',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('Acceptance and Commitment Therapy (ACT)', 'Acceptance and Commitment Therapy (ACT)'),
    aliases: [t('acceptatie- en commitmenttherapie', 'acceptance and commitment therapy')],
    plainExplanation: t(
      'ACT leert je ruimte te maken voor moeilijke ervaringen en tegelijk stappen te zetten naar wat belangrijk voor je is.',
      'ACT teaches you to make room for difficult experiences while taking steps toward what matters to you.',
    ),
    deeperExplanation: t(
      'ACT is een gedragstherapeutische benadering die psychologische flexibiliteit oefent. Het doel is niet om alle klachten weg te krijgen, maar om anders met gedachten en gevoelens om te gaan zodat ze je leven minder besturen.',
      'ACT is a behavioural therapy approach that develops psychological flexibility. Its aim is not to remove every symptom, but to change how you respond to thoughts and feelings so they have less control over your life.',
    ),
    example: t(
      'Je voelt spanning voor een afspraak, merkt die spanning op en gaat toch omdat contact met anderen belangrijk voor je is.',
      'You feel tense before an appointment, notice the tension, and still go because connecting with others matters to you.',
    ),
    misconception: t(
      'ACT betekent niet dat je alles prettig moet vinden of nooit een probleem mag oplossen.',
      'ACT does not mean that you must like everything or that you should never solve a problem.',
    ),
    safetyNote: t(
      'Deze uitleg is psycho-educatie en geen diagnose of persoonlijke behandeling. Zoek passende hulp als klachten je veiligheid of dagelijks functioneren ernstig bedreigen.',
      'This explanation is psychoeducation, not a diagnosis or personal treatment. Seek appropriate help if symptoms seriously threaten your safety or daily functioning.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['psychological-flexibility', 'acceptance', 'values', 'committed-action'],
    relatedSkillIds: ['acceptatie-toestaan', 'waarden-verhelderen', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'psychological-flexibility',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('psychologische flexibiliteit', 'psychological flexibility'),
    aliases: [t('mentale wendbaarheid', 'mental flexibility')],
    plainExplanation: t(
      'Psychologische flexibiliteit is kunnen merken wat er nu gebeurt en kiezen wat in deze situatie helpt en bij je waarden past.',
      'Psychological flexibility is noticing what is happening now and choosing what helps in this situation and fits your values.',
    ),
    deeperExplanation: t(
      'Flexibiliteit ontstaat door zes samenwerkende processen: contact met het huidige moment, acceptatie, defusie, zelf-als-context, waarden en toegewijd handelen. Het gaat om passend kunnen schakelen, niet om altijd kalm of positief zijn.',
      'Flexibility grows through six interacting processes: present-moment contact, acceptance, defusion, self-as-context, values, and committed action. It means adapting effectively, not staying calm or positive all the time.',
    ),
    example: t(
      'Na kritiek voel je schaamte. Je pauzeert, luistert, stelt een vraag en kiest daarna hoe je eerlijk wilt reageren.',
      'After criticism you feel shame. You pause, listen, ask a question, and then choose how you want to respond honestly.',
    ),
    misconception: t(
      'Flexibiliteit is niet hetzelfde als toegeven, geen grenzen hebben of steeds van mening veranderen.',
      'Flexibility is not the same as giving in, having no boundaries, or constantly changing your mind.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['present-moment', 'acceptance', 'cognitive-defusion', 'self-as-context', 'values', 'committed-action'],
    relatedSkillIds: ['hier-en-nu', 'acceptatie-toestaan', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'present-moment',
    frameworks: ['ACT', 'gedeeld'],
    tier: 'kern',
    formalName: t('contact met het huidige moment', 'contact with the present moment'),
    aliases: [t('hier-en-nu', 'here and now'), t('bewuste aandacht', 'aware attention')],
    plainExplanation: t(
      'Je brengt je aandacht bewust terug naar wat je nu ziet, hoort, voelt en doet.',
      'You deliberately bring your attention back to what you can see, hear, feel, and do right now.',
    ),
    deeperExplanation: t(
      'Contact met het huidige moment betekent dat je aandacht soepel richt op wat nu relevant is. Je kunt herinneringen en plannen wel opmerken, zonder er automatisch in te verdwijnen.',
      'Present-moment contact means directing attention flexibly toward what is relevant now. You can still notice memories and plans without automatically getting lost in them.',
    ),
    example: t(
      'Tijdens het afwassen merk je dat je een gesprek herhaalt in je hoofd. Je voelt het warme water en gaat verder met één bord tegelijk.',
      'While washing dishes, you notice that you are replaying a conversation. You feel the warm water and continue one plate at a time.',
    ),
    misconception: t(
      'In het nu zijn betekent niet dat je nooit over het verleden nadenkt of de toekomst plant.',
      'Being present does not mean never reflecting on the past or planning for the future.',
    ),
    safetyNote: t(
      'Sterk naar binnen richten kan bij sommige mensen onrust of herbelevingen versterken. Kies dan een korte, uitwendige grondingsoefening en stop als dat nodig is.',
      'Strong inward focus can increase distress or flashbacks for some people. Choose a brief external grounding exercise instead and stop if needed.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['mindfulness', 'past-future-dominance', 'psychological-flexibility'],
    relatedSkillIds: ['hier-en-nu', 'gronden-54321', 'afstand-observeren'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'acceptance',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('acceptatie', 'acceptance'),
    aliases: [t('ruimte maken', 'making room'), t('toestaan', 'allowing')],
    plainExplanation: t(
      'Acceptatie is een moeilijke gedachte, emotie of lichamelijke sensatie laten bestaan zonder er direct tegen te vechten.',
      'Acceptance means allowing a difficult thought, emotion, or body sensation to be present without immediately fighting it.',
    ),
    deeperExplanation: t(
      'Acceptatie is een actieve houding tegenover ervaringen die er al zijn en niet direct veranderd hoeven of kunnen worden. De aandacht verschuift van de innerlijke strijd naar gedrag dat op dat moment bruikbaar is.',
      'Acceptance is an active stance toward experiences that are already present and do not need to, or cannot, change immediately. Attention shifts from the inner struggle to behaviour that is useful in that moment.',
    ),
    example: t(
      'Je merkt een knoop in je maag voor een lastig telefoontje. Je ademt, geeft de spanning ruimte en belt met een vooraf opgeschreven openingszin.',
      'You notice a knot in your stomach before a difficult phone call. You breathe, make room for the tension, and call using an opening sentence you prepared.',
    ),
    misconception: t(
      'Acceptatie is geen goedkeuring, berusting of opdracht om in een onveilige situatie te blijven.',
      'Acceptance is not approval, resignation, or an instruction to remain in an unsafe situation.',
    ),
    safetyNote: t(
      'Neem bij direct gevaar eerst praktische veiligheidsstappen. Innerlijke acceptatie vervangt geen bescherming, medische zorg of crisissteun.',
      'When there is immediate danger, take practical safety steps first. Inner acceptance does not replace protection, medical care, or crisis support.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['willingness', 'experiential-avoidance', 'committed-action'],
    relatedSkillIds: ['acceptatie-toestaan', 'adem-vertragen'],
    primaryTheoryLessonId: 'w03-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'cognitive-defusion',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('cognitieve defusie', 'cognitive defusion'),
    aliases: [t('afstand van gedachten', 'distance from thoughts'), t('ontkoppelen', 'unhooking')],
    plainExplanation: t(
      'Bij defusie merk je een gedachte op als woorden of beelden in je hoofd, niet automatisch als feit of opdracht.',
      'With defusion, you notice a thought as words or images in your mind, not automatically as a fact or command.',
    ),
    deeperExplanation: t(
      'Defusie verandert vooral de invloed van een gedachte, niet per se de inhoud ervan. Daardoor ontstaat ruimte om gedrag te kiezen op basis van de situatie en je waarden.',
      'Defusion mainly changes a thought’s influence, not necessarily its content. This creates room to choose behaviour based on the situation and your values.',
    ),
    example: t(
      'In plaats van “ik kan dit niet” zeg je: “ik merk dat mijn hoofd de gedachte geeft dat ik dit niet kan”, en je probeert de eerste kleine stap.',
      'Instead of “I cannot do this,” you say, “I notice my mind is giving me the thought that I cannot do this,” and try the first small step.',
    ),
    misconception: t(
      'Defusie is niet doen alsof een gedachte onzin is en ook niet dezelfde techniek als bewijs voor en tegen een gedachte onderzoeken.',
      'Defusion is not pretending a thought is nonsense, and it is not the same technique as examining evidence for and against a thought.',
    ),
    safetyNote: t(
      'Controleer praktische signalen van gevaar nog steeds serieus. Afstand nemen van een gedachte betekent niet dat je alle waarschuwingen negeert.',
      'Continue to take practical signs of danger seriously. Gaining distance from a thought does not mean ignoring every warning.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['cognitive-fusion', 'function-versus-content', 'present-moment'],
    relatedSkillIds: ['defusie-afstand-van-gedachten', 'gedachten-uitdagen'],
    primaryTheoryLessonId: 'w04-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'self-as-context',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('zelf-als-context', 'self-as-context'),
    aliases: [t('waarnemend zelf', 'observing self'), t('perspectiefnemend zelf', 'perspective-taking self')],
    plainExplanation: t(
      'Je bent de persoon die gedachten, gevoelens en rollen kan opmerken; je bent niet beperkt tot één gedachte, gevoel of label.',
      'You are the person who can notice thoughts, feelings, and roles; you are not limited to one thought, feeling, or label.',
    ),
    deeperExplanation: t(
      'Zelf-als-context is het stabiele perspectief van waaruit wisselende ervaringen worden waargenomen. Dit perspectief helpt om minder vast te zitten in een verhaal over wie je zou zijn.',
      'Self-as-context is the stable perspective from which changing experiences are noticed. This perspective helps you become less stuck in a story about who you supposedly are.',
    ),
    example: t(
      'Je denkt “ik ben mislukt” en merkt daarna: “er is nu een pijnlijk verhaal over mislukken, en ik kan ook zien wat mijn volgende stap is.”',
      'You think “I am a failure” and then notice, “there is a painful story about failure right now, and I can also see what my next step is.”',
    ),
    misconception: t(
      'Zelf-als-context betekent niet dat je geen persoonlijkheid, geschiedenis of verantwoordelijkheid hebt.',
      'Self-as-context does not mean that you have no personality, history, or responsibility.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['self-as-content', 'self-as-process', 'cognitive-defusion'],
    relatedSkillIds: ['waarnemend-zelf', 'afstand-observeren'],
    primaryTheoryLessonId: 'w05-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'values',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('waarden', 'values'),
    aliases: [t('gekozen richting', 'chosen direction'), t('wat belangrijk is', 'what matters')],
    plainExplanation: t(
      'Waarden zijn kwaliteiten die je wilt laten zien in hoe je leeft, zoals zorgzaam, nieuwsgierig of betrouwbaar zijn.',
      'Values are qualities you want to express in how you live, such as being caring, curious, or reliable.',
    ),
    deeperExplanation: t(
      'Een waarde geeft richting aan herhaald gedrag en kan niet definitief worden afgevinkt. Waarden worden gekozen, concreet gemaakt per levensgebied en onderscheiden van regels die vooral door druk of angst worden gevolgd.',
      'A value guides repeated behaviour and cannot be permanently checked off. Values are chosen, made concrete within life areas, and distinguished from rules followed mainly because of pressure or fear.',
    ),
    example: t(
      'Als “aandachtig contact” een waarde is, leg je tijdens het eten tien minuten je telefoon weg en luister je naar de ander.',
      'If “attentive connection” is a value, you put your phone away for ten minutes during dinner and listen to the other person.',
    ),
    misconception: t(
      'Een waarde is geen perfect eindresultaat, gevoel, moreel oordeel of lijstje van wat anderen van je verwachten.',
      'A value is not a perfect end result, a feeling, a moral judgement, or a list of what others expect from you.',
    ),
    safetyNote: t(
      'Een gekozen waarde hoeft nooit te betekenen dat je grenzen, gezondheid of veiligheid opoffert.',
      'A chosen value never has to mean sacrificing your boundaries, health, or safety.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['value-goal-action', 'unclear-imposed-values', 'committed-action'],
    relatedSkillIds: ['waarden-verhelderen', 'grens-aangeven'],
    primaryTheoryLessonId: 'w07-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'committed-action',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('toegewijd handelen', 'committed action'),
    aliases: [t('waardegerichte actie', 'values-guided action'), t('betrokken handelen', 'engaged action')],
    plainExplanation: t(
      'Toegewijd handelen is haalbare stappen zetten in de richting van je waarden, ook als ongemak meereist.',
      'Committed action means taking workable steps toward your values, even when discomfort comes along.',
    ),
    deeperExplanation: t(
      'Toegewijd handelen combineert een gekozen richting met concreet gedrag, leren van gevolgen en opnieuw kiezen na een terugval. Volhouden is flexibel: een plan mag worden aangepast als het niet werkt.',
      'Committed action combines a chosen direction with concrete behaviour, learning from consequences, and choosing again after a setback. Persistence is flexible: a plan may be adjusted when it does not work.',
    ),
    example: t(
      'Je waardeert gezondheid en wandelt vandaag vijf minuten. Bij slecht weer kies je een korte ronde binnenshuis in plaats van het hele plan op te geven.',
      'You value health and walk for five minutes today. In bad weather, you choose a short indoor round instead of abandoning the whole plan.',
    ),
    misconception: t(
      'Commitment betekent niet dat je koste wat kost doorgaat met een onveilig, schadelijk of onwerkbaar plan.',
      'Commitment does not mean continuing with an unsafe, harmful, or unworkable plan at any cost.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['values', 'choice-freedom', 'workability', 'inaction-impulsivity-rigid-persistence'],
    relatedSkillIds: ['toegewijd-handelen', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w08-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'experiential-avoidance',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('experiëntiële vermijding', 'experiential avoidance'),
    aliases: [t('ervaringsvermijding', 'experience avoidance'), t('innerlijke vermijding', 'inner avoidance')],
    plainExplanation: t(
      'Dit is proberen van onprettige gedachten, gevoelens of lichamelijke sensaties af te komen, terwijl die strijd je leven kleiner maakt.',
      'This means trying to get rid of unpleasant thoughts, feelings, or body sensations while that struggle makes your life smaller.',
    ),
    deeperExplanation: t(
      'Vermijding is niet automatisch een probleem. Ze wordt onflexibel wanneer snelle opluchting steeds belangrijker wordt dan gevolgen op langere termijn en waardevolle activiteiten verdwijnen.',
      'Avoidance is not automatically a problem. It becomes inflexible when quick relief repeatedly outweighs longer-term consequences and valued activities disappear.',
    ),
    example: t(
      'Je zegt elke sociale afspraak af om spanning te voorkomen. De spanning zakt even, maar je raakt steeds meer geïsoleerd.',
      'You cancel every social plan to avoid anxiety. The anxiety drops briefly, but you become increasingly isolated.',
    ),
    misconception: t(
      'Niet elke pauze, afleiding of vermijding is ongezond; weggaan uit gevaar is juist functioneel.',
      'Not every pause, distraction, or avoidance is unhealthy; leaving danger is functional.',
    ),
    safetyNote: t(
      'Gebruik acceptatie nooit als reden om echt gevaar te benaderen. Beoordeel eerst of de situatie veilig genoeg is.',
      'Never use acceptance as a reason to approach real danger. First assess whether the situation is safe enough.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['acceptance', 'willingness', 'control-agenda', 'workability'],
    relatedSkillIds: ['acceptatie-toestaan', 'veilige-plek'],
    primaryTheoryLessonId: 'w03-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'cognitive-fusion',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('cognitieve fusie', 'cognitive fusion'),
    aliases: [t('samenvallen met gedachten', 'being fused with thoughts'), t('vastgehaakt zijn', 'being hooked')],
    plainExplanation: t(
      'Bij fusie voelt een gedachte zo letterlijk en dwingend dat ze je gedrag bijna automatisch bepaalt.',
      'In fusion, a thought feels so literal and compelling that it almost automatically directs your behaviour.',
    ),
    deeperExplanation: t(
      'Fusie beschrijft de relatie met taal: woorden, regels of beelden krijgen meer invloed dan wat de huidige situatie laat zien. De vraag is niet alleen of een gedachte waar is, maar ook wat volgen ervan nu doet.',
      'Fusion describes a relationship with language: words, rules, or images gain more influence than what the present situation shows. The question is not only whether a thought is true, but also what following it does now.',
    ),
    example: t(
      'De gedachte “ik mag geen fout maken” zorgt ervoor dat je een taak uren uitstelt, ook al zou een eerste versie voldoende zijn.',
      'The thought “I must not make a mistake” leads you to postpone a task for hours, even though a first draft would be enough.',
    ),
    misconception: t(
      'Fusie betekent niet dat je dom bent of dat al je gedachten onwaar zijn.',
      'Fusion does not mean that you are unintelligent or that all your thoughts are false.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['cognitive-defusion', 'function-versus-content', 'self-as-content'],
    relatedSkillIds: ['defusie-afstand-van-gedachten', 'gedachten-uitdagen'],
    primaryTheoryLessonId: 'w04-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'past-future-dominance',
    frameworks: ['ACT'],
    tier: 'ondersteunend',
    formalName: t('overheersing door verleden of toekomst', 'dominance of the past or future'),
    aliases: [t('starre aandacht', 'rigid attention'), t('vastzitten in toen of straks', 'being stuck in then or later')],
    plainExplanation: t(
      'Herinneringen, zorgen of voorspellingen nemen zoveel aandacht over dat je nauwelijks reageert op wat er nu gebeurt.',
      'Memories, worries, or predictions take over so much attention that you barely respond to what is happening now.',
    ),
    deeperExplanation: t(
      'Het probleem is niet denken over tijd, maar starheid: aandacht kan niet meer terug naar informatie en keuzemogelijkheden in het huidige moment.',
      'The problem is not thinking across time, but rigidity: attention can no longer return to information and choices in the present moment.',
    ),
    example: t(
      'Tijdens een gesprek ben je bezig met wat je straks verkeerd zou kunnen zeggen en hoor je de vraag van de ander niet meer.',
      'During a conversation, you are busy with what you might say wrong later and no longer hear the other person’s question.',
    ),
    misconception: t(
      'Herinneren, vooruitdenken en risico’s plannen zijn niet fout; het gaat om kunnen schakelen.',
      'Remembering, thinking ahead, and planning for risks are not wrong; the issue is being able to shift.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['present-moment', 'mindfulness', 'psychological-flexibility'],
    relatedSkillIds: ['hier-en-nu', 'gronden-54321'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'self-as-content',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('zelf-als-inhoud', 'self-as-content'),
    aliases: [t('conceptueel zelf', 'conceptualised self'), t('zelfverhaal', 'self-story')],
    plainExplanation: t(
      'Je behandelt een verhaal of label over jezelf alsof het je volledige en vaste identiteit is.',
      'You treat a story or label about yourself as if it were your complete and fixed identity.',
    ),
    deeperExplanation: t(
      'Zelfverhalen helpen om ervaringen te ordenen, maar kunnen gedrag beperken wanneer ze letterlijk en onveranderlijk worden gevolgd. Een label kan informatie geven zonder alle mogelijkheden te bepalen.',
      'Self-stories help organise experience, but can restrict behaviour when followed literally and rigidly. A label can provide information without determining every possibility.',
    ),
    example: t(
      'Omdat je jezelf “geen sporter” noemt, sla je een rustige wandeling over die eigenlijk haalbaar en belangrijk voor je is.',
      'Because you call yourself “not an active person,” you skip a gentle walk that is actually possible and important to you.',
    ),
    misconception: t(
      'Het doel is niet om je levensverhaal, rollen of een nuttige diagnose te ontkennen.',
      'The aim is not to deny your life story, roles, or a useful diagnosis.',
    ),
    safetyNote: t(
      'Verander medicatie of professionele ondersteuning niet op basis van een oefening over labels.',
      'Do not change medication or professional support based on an exercise about labels.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['self-as-context', 'self-as-process', 'cognitive-fusion'],
    relatedSkillIds: ['waarnemend-zelf', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w05-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'unclear-imposed-values',
    frameworks: ['ACT'],
    tier: 'ondersteunend',
    formalName: t('onduidelijke of opgelegde waarden', 'unclear or imposed values'),
    aliases: [t('leven volgens moeten', 'living by shoulds'), t('verloren richting', 'lost direction')],
    plainExplanation: t(
      'Je weet niet goed wat jij belangrijk vindt, of je leeft vooral volgens regels en verwachtingen van anderen.',
      'You are unsure what matters to you, or you mainly live by other people’s rules and expectations.',
    ),
    deeperExplanation: t(
      'Gedrag kan dan worden gestuurd door vermijden van schuld, afwijzing of kritiek in plaats van een bewust gekozen kwaliteit van handelen. Waarden verhelderen betekent onderzoeken, niet één perfect antwoord vinden.',
      'Behaviour may then be driven by avoiding guilt, rejection, or criticism rather than by a deliberately chosen quality of action. Clarifying values means exploring, not finding one perfect answer.',
    ),
    example: t(
      'Je volgt een opleiding alleen omdat “dat hoort”, maar hebt nooit onderzocht welke vorm van leren of bijdragen bij jou past.',
      'You pursue a course only because “that is what people do,” but have never explored what kind of learning or contribution suits you.',
    ),
    misconception: t(
      'Invloed van familie, cultuur of advies maakt een waarde niet automatisch onecht; jij onderzoekt of je die richting bewust wilt kiezen.',
      'Influence from family, culture, or advice does not automatically make a value inauthentic; you explore whether you consciously want to choose that direction.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['values', 'value-goal-action', 'choice-freedom'],
    relatedSkillIds: ['waarden-verhelderen', 'nee-zeggen'],
    primaryTheoryLessonId: 'w07-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'inaction-impulsivity-rigid-persistence',
    frameworks: ['ACT'],
    tier: 'ondersteunend',
    formalName: t('inactiviteit, impulsiviteit of star volhouden', 'inaction, impulsivity, or rigid persistence'),
    aliases: [t('onwerkbare actiepatronen', 'unworkable action patterns')],
    plainExplanation: t(
      'Je komt niet in actie, reageert meteen op een impuls, of blijft doorgaan terwijl aanpassen beter zou werken.',
      'You do not act, react immediately to an impulse, or keep going when adapting would work better.',
    ),
    deeperExplanation: t(
      'Deze drie patronen kunnen de gedragskant van psychologische inflexibiliteit vormen. Ze raken los van gekozen waarden en actuele gevolgen: er is te weinig beweging, te weinig pauze of te weinig bijsturing.',
      'These three patterns can form the behavioural side of psychological inflexibility. They become disconnected from chosen values and current consequences: there is too little movement, too little pause, or too little adjustment.',
    ),
    example: t(
      'Je stelt een rekening weken uit, koopt daarna impulsief iets om je beter te voelen en houdt vervolgens een onhaalbaar streng budget vol.',
      'You postpone a bill for weeks, then buy something impulsively to feel better, and afterwards stick to an unrealistically strict budget.',
    ),
    misconception: t(
      'Het zijn beschrijvingen van gedragspatronen, geen vaste persoonlijkheidstypen of morele fouten.',
      'These are descriptions of behaviour patterns, not fixed personality types or moral failures.',
    ),
    safetyNote: t(
      'Bij impulsen rond zelfbeschadiging, geweld of ander direct gevaar is een veiligheidsplan en menselijke hulp belangrijker dan alleen een zelfhulpoefening.',
      'For urges involving self-harm, violence, or other immediate danger, a safety plan and human support matter more than a self-help exercise alone.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['committed-action', 'choice-freedom', 'workability'],
    relatedSkillIds: ['toegewijd-handelen', 'problemen-aanpakken', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w08-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'willingness',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('bereidheid', 'willingness'),
    aliases: [t('willen toelaten', 'being willing'), t('openheid voor ongemak', 'openness to discomfort')],
    plainExplanation: t(
      'Bereidheid is bewust ruimte willen geven aan het ongemak dat bij een belangrijke stap kan horen.',
      'Willingness means deliberately allowing the discomfort that may come with an important step.',
    ),
    deeperExplanation: t(
      'Bereidheid is acceptatie in dienst van gekozen gedrag. Je kiest niet voor pijn als doel, maar voor een waardevolle handeling en laat de onvermijdelijke innerlijke ervaring meereizen.',
      'Willingness is acceptance in the service of chosen behaviour. You do not choose pain as a goal; you choose a valued action and allow the unavoidable inner experience to come along.',
    ),
    example: t(
      'Je bent bereid enige onzekerheid te voelen terwijl je een eerlijke grens aangeeft.',
      'You are willing to feel some uncertainty while stating an honest boundary.',
    ),
    misconception: t(
      'Bereidheid is geen eis om alle pijn op te zoeken of onbeperkt te verdragen.',
      'Willingness is not a demand to seek out or tolerate unlimited pain.',
    ),
    safetyNote: t(
      'Kies alleen ongemak dat past bij een veilige, haalbare stap. Bescherming tegen misbruik of gevaar gaat voor.',
      'Only choose discomfort that belongs to a safe, manageable step. Protection from abuse or danger comes first.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['acceptance', 'experiential-avoidance', 'values', 'committed-action'],
    relatedSkillIds: ['acceptatie-toestaan', 'grens-aangeven'],
    primaryTheoryLessonId: 'w03-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'workability',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('werkbaarheid', 'workability'),
    aliases: [t('doet het wat je nodig hebt?', 'does it do what you need?'), t('bruikbaarheid in context', 'usefulness in context')],
    plainExplanation: t(
      'Werkbaarheid vraagt: helpt dit gedrag mij hier en op langere termijn in de richting die ik kies?',
      'Workability asks: does this behaviour help me here and over time in the direction I choose?',
    ),
    deeperExplanation: t(
      'ACT beoordeelt gedrag in zijn context en op zijn gevolgen, niet alleen als goed of fout. Dezelfde actie kan in de ene situatie bruikbaar zijn en in een andere niet.',
      'ACT evaluates behaviour in its context and by its consequences, not simply as right or wrong. The same action may be useful in one situation and not in another.',
    ),
    example: t(
      'Een avond rust nemen helpt na uitputting, maar een maand alle contacten vermijden brengt je verder van verbinding. De functie en gevolgen verschillen.',
      'Taking one evening to rest helps after exhaustion, but avoiding all contact for a month moves you away from connection. The function and consequences differ.',
    ),
    misconception: t(
      'Werkbaar betekent niet “direct prettig” en ook niet dat waarheid, ethiek of veiligheid er niet toe doen.',
      'Workable does not mean “pleasant right away,” nor does it mean that truth, ethics, or safety do not matter.',
    ),
    sourceIds: philosophySources,
    relatedConceptIds: ['function-versus-content', 'values', 'committed-action', 'control-agenda'],
    relatedSkillIds: ['problemen-aanpakken', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w03-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'private-experience',
    frameworks: ['ACT', 'algemeen'],
    tier: 'ondersteunend',
    formalName: t('innerlijke ervaring', 'private experience'),
    aliases: [t('privégebeurtenis', 'private event'), t('binnenwereld', 'inner world')],
    plainExplanation: t(
      'Een innerlijke ervaring is iets dat jij van binnen merkt, zoals een gedachte, herinnering, emotie, drang of lichamelijke sensatie.',
      'A private experience is something you notice internally, such as a thought, memory, emotion, urge, or body sensation.',
    ),
    deeperExplanation: t(
      'Het woord “privé” betekent dat anderen de ervaring niet rechtstreeks kunnen waarnemen; het betekent niet geheim of onbelangrijk. Innerlijke ervaringen kunnen gedrag beïnvloeden en tegelijk zelf als ervaringen worden opgemerkt.',
      'The word “private” means that others cannot directly observe the experience; it does not mean secret or unimportant. Private experiences can influence behaviour and can also be noticed as experiences in their own right.',
    ),
    example: t(
      'Je collega ziet dat je stil bent, maar alleen jij merkt rechtstreeks de herinnering, hartslag en gedachte die op dat moment aanwezig zijn.',
      'Your colleague sees that you are quiet, but only you directly notice the memory, heartbeat, and thought present at that moment.',
    ),
    misconception: t(
      'Een innerlijke ervaring is niet automatisch waar, onwaar, ziek of gevaarlijk; dat vraagt aparte beoordeling.',
      'A private experience is not automatically true, false, disordered, or dangerous; that requires separate assessment.',
    ),
    safetyNote: t(
      'Een sterke drang is een innerlijke ervaring, maar kan wel om directe veiligheidsactie vragen als jij of iemand anders gevaar loopt.',
      'A strong urge is a private experience, but it can still require immediate safety action if you or someone else is at risk.',
    ),
    sourceIds: philosophySources,
    relatedConceptIds: ['acceptance', 'cognitive-defusion', 'mindfulness'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'function-versus-content',
    frameworks: ['ACT'],
    tier: 'ondersteunend',
    formalName: t('functie tegenover inhoud', 'function versus content'),
    aliases: [t('wat doet het tegenover wat zegt het?', 'what does it do versus what does it say?')],
    plainExplanation: t(
      'Inhoud is wat een gedachte of gedrag zegt of lijkt; functie is welk effect het in deze situatie heeft.',
      'Content is what a thought or behaviour says or looks like; function is the effect it has in this situation.',
    ),
    deeperExplanation: t(
      'Een functionele analyse kijkt naar aanleiding, gedrag en gevolgen. Daardoor kan hetzelfde zichtbare gedrag verschillende functies hebben en vraagt een helpende reactie altijd om context.',
      'A functional analysis looks at context, behaviour, and consequences. The same visible behaviour can therefore serve different functions, and a helpful response always requires context.',
    ),
    example: t(
      'Een wandeling kan herstel zijn na een drukke dag of een manier om elk moeilijk gesprek te ontlopen. De handeling is gelijk, de functie verschilt.',
      'A walk can be recovery after a busy day or a way to avoid every difficult conversation. The action is the same; its function differs.',
    ),
    misconception: t(
      'Aandacht voor functie betekent niet dat feiten of de letterlijke inhoud nooit belangrijk zijn.',
      'Focusing on function does not mean facts or literal content never matter.',
    ),
    sourceIds: philosophySources,
    relatedConceptIds: ['workability', 'cognitive-defusion', 'functional-contextualism'],
    relatedSkillIds: ['afstand-observeren', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w04-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'mindfulness',
    frameworks: ['ACT', 'gedeeld'],
    tier: 'kern',
    formalName: t('mindfulness', 'mindfulness'),
    aliases: [t('opmerkzame aanwezigheid', 'mindful awareness'), t('bewust waarnemen', 'conscious noticing')],
    plainExplanation: t(
      'Mindfulness is bewust opmerken wat er nu gebeurt, met een open houding en zonder meteen op automatische piloot te reageren.',
      'Mindfulness means deliberately noticing what is happening now with an open stance, without immediately reacting on autopilot.',
    ),
    deeperExplanation: t(
      'Binnen ACT is mindfulness geen enkel trucje maar een combinatie van aandacht, openheid en perspectief. Je oefent om ervaringen te observeren en daarna passend te handelen.',
      'Within ACT, mindfulness is not one trick but a combination of attention, openness, and perspective. You practise observing experiences and then acting effectively.',
    ),
    example: t(
      'Je merkt tijdens een discussie warme wangen, snelle gedachten en de neiging om te onderbreken. Je pauzeert één ademhaling en luistert verder.',
      'During an argument, you notice warm cheeks, rapid thoughts, and the urge to interrupt. You pause for one breath and keep listening.',
    ),
    misconception: t(
      'Mindfulness is geen garantie op ontspanning, een leeg hoofd of voortdurend neutraal voelen.',
      'Mindfulness does not guarantee relaxation, an empty mind, or feeling neutral all the time.',
    ),
    safetyNote: t(
      'Oefen korter of richt aandacht op de buitenwereld als stilzitten of naar binnen kijken je duidelijk ontregelt.',
      'Practise for less time or focus outward if sitting still or turning inward clearly destabilises you.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['present-moment', 'acceptance', 'cognitive-defusion', 'self-as-context'],
    relatedSkillIds: ['hier-en-nu', 'afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'value-goal-action',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('waarde, doel en actie', 'value, goal, and action'),
    aliases: [t('richting, bestemming en stap', 'direction, destination, and step')],
    plainExplanation: t(
      'Een waarde geeft richting, een doel beschrijft een haalbaar resultaat en een actie is wat je concreet doet.',
      'A value gives direction, a goal describes an achievable result, and an action is what you concretely do.',
    ),
    deeperExplanation: t(
      'Deze drie niveaus horen bij elkaar maar zijn niet uitwisselbaar. Een doel kan worden bereikt of aangepast; de waarde kan daarna nieuwe doelen blijven sturen, terwijl acties klein en direct observeerbaar zijn.',
      'These three levels belong together but are not interchangeable. A goal can be reached or revised; the value can continue to guide new goals, while actions are small and directly observable.',
    ),
    example: t(
      'Waarde: betrokken zijn. Doel: deze maand met een vriend afspreken. Actie: vanavond een bericht sturen met twee data.',
      'Value: being engaged. Goal: meet a friend this month. Action: send a message tonight with two suggested dates.',
    ),
    misconception: t(
      '“Gelukkig zijn” is meestal geen volledig bestuurbare actie; beschrijf welk gedrag die gewenste richting zichtbaar maakt.',
      '“Being happy” is usually not a fully controllable action; describe what behaviour would make that desired direction visible.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['values', 'committed-action', 'choice-freedom'],
    relatedSkillIds: ['waarden-verhelderen', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w07-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'choice-freedom',
    frameworks: ['ACT'],
    tier: 'ondersteunend',
    formalName: t('keuzevrijheid', 'freedom to choose'),
    aliases: [t('keuzeruimte', 'choice space'), t('bewust kiezen', 'choosing deliberately')],
    plainExplanation: t(
      'Keuzevrijheid is de kleine ruimte tussen wat je ervaart en hoe je vervolgens handelt.',
      'Freedom to choose is the small space between what you experience and how you act next.',
    ),
    deeperExplanation: t(
      'ACT vergroot gedragsmogelijkheden door automatische reacties eerst zichtbaar te maken. Keuzevrijheid is altijd begrensd door omstandigheden, mogelijkheden en veiligheid, maar ook binnen grenzen kan soms een volgende stap worden gekozen.',
      'ACT expands behavioural options by first making automatic reactions visible. Choice is always limited by circumstances, abilities, and safety, yet even within limits a next step can sometimes be chosen.',
    ),
    example: t(
      'Je kunt een nare e-mail niet ongedaan maken, maar je kunt wel kiezen om eerst af te koelen, advies te vragen en morgen te antwoorden.',
      'You cannot undo an upsetting email, but you can choose to cool down first, ask for advice, and reply tomorrow.',
    ),
    misconception: t(
      'Keuzevrijheid betekent niet dat je alles beheerst of schuld hebt aan omstandigheden, ziekte of emoties.',
      'Freedom to choose does not mean that you control everything or are to blame for circumstances, illness, or emotions.',
    ),
    safetyNote: t(
      'Bij dwang, afhankelijkheid of acuut gevaar kan de feitelijke keuzeruimte zeer klein zijn; hulp en bescherming kunnen dan nodig zijn.',
      'Under coercion, dependency, or immediate danger, real choice may be very limited; support and protection may then be necessary.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['psychological-flexibility', 'committed-action', 'value-goal-action'],
    relatedSkillIds: ['toegewijd-handelen', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w08-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'functional-contextualism',
    frameworks: ['ACT'],
    tier: 'verdieping',
    formalName: t('functioneel contextualisme', 'functional contextualism'),
    aliases: [t('contextuele gedragsvisie', 'contextual behavioural view')],
    plainExplanation: t(
      'Deze visie onderzoekt wat gedrag doet in een bepaalde situatie en of dat helpt voor een gekozen doel.',
      'This view examines what behaviour does in a particular situation and whether it helps toward a chosen aim.',
    ),
    deeperExplanation: t(
      'Functioneel contextualisme is de wetenschapsfilosofische basis van ACT. Gedrag wordt als een geheel in historische en actuele context bestudeerd, met als praktische maatstaf of voorspellen en beïnvloeden voor een expliciet doel bruikbaar is.',
      'Functional contextualism is the philosophy of science underlying ACT. Behaviour is studied as a whole within historical and current context, with practical prediction and influence assessed against an explicit aim.',
    ),
    example: t(
      'In plaats van “uitstel is luiheid” onderzoek je wanneer het voorkomt, wat eraan voorafgaat, welke opluchting volgt en welke aanpak echt helpt.',
      'Instead of “procrastination is laziness,” you examine when it occurs, what comes before it, what relief follows, and which approach actually helps.',
    ),
    misconception: t(
      'Contextueel kijken betekent niet dat alles relatief is of dat feiten, waarden en ethiek er niet toe doen.',
      'A contextual view does not mean that everything is relative or that facts, values, and ethics do not matter.',
    ),
    sourceIds: ['acbs-philosophical-roots'],
    relatedConceptIds: ['function-versus-content', 'workability', 'rft'],
    relatedSkillIds: ['problemen-aanpakken'],
    primaryTheoryLessonId: 'w12-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'rft',
    frameworks: ['ACT'],
    tier: 'verdieping',
    formalName: t('Relational Frame Theory (RFT)', 'Relational Frame Theory (RFT)'),
    aliases: [t('relationele kadertheorie', 'relational framing theory')],
    plainExplanation: t(
      'RFT is een leertheorie over hoe mensen via taal verbanden leggen en hoe die verbanden gedrag kunnen beïnvloeden.',
      'RFT is a learning theory about how people create relationships through language and how those relationships can influence behaviour.',
    ),
    deeperExplanation: t(
      'RFT beschrijft aangeleerd relationeel reageren: gebeurtenissen krijgen betekenis via relaties zoals groter-kleiner, vroeger-later of ik-jij. Zulke relaties kunnen de werking van woorden en situaties veranderen, ook zonder directe ervaring.',
      'RFT describes learned relational responding: events gain meaning through relations such as bigger-smaller, before-after, or self-other. These relations can change how words and situations function, even without direct experience.',
    ),
    example: t(
      'Als “fout” in je leerervaring sterk verbonden raakt met “waardeloos”, kan een kleine correctie later veel schaamte oproepen.',
      'If “mistake” becomes strongly linked with “worthless” in your learning history, a small correction may later evoke intense shame.',
    ),
    misconception: t(
      'Je hoeft RFT niet volledig te begrijpen om ACT-oefeningen bruikbaar toe te passen.',
      'You do not need to understand RFT fully to use ACT exercises effectively.',
    ),
    sourceIds: ['acbs-philosophical-roots'],
    relatedConceptIds: ['functional-contextualism', 'cognitive-fusion', 'cognitive-defusion'],
    relatedSkillIds: ['defusie-afstand-van-gedachten'],
    primaryTheoryLessonId: 'w12-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'self-as-process',
    frameworks: ['ACT'],
    tier: 'verdieping',
    formalName: t('zelf-als-proces', 'self-as-process'),
    aliases: [t('doorlopend zelfbewustzijn', 'ongoing self-awareness')],
    plainExplanation: t(
      'Zelf-als-proces is van moment tot moment precies kunnen benoemen wat je nu denkt, voelt en doet.',
      'Self-as-process means being able to describe precisely what you are thinking, feeling, and doing from moment to moment.',
    ),
    deeperExplanation: t(
      'Dit is flexibel, direct zelfbewustzijn zonder meteen een vast oordeel over de persoon te maken. Het vormt een brug tussen opmerkzaamheid en het ruimere perspectief van zelf-als-context.',
      'This is flexible, direct self-awareness without immediately making a fixed judgement about the person. It forms a bridge between noticing and the broader perspective of self-as-context.',
    ),
    example: t(
      'Je zegt: “ik merk spanning, de gedachte dat ik moet vluchten en mijn handen die naar mijn telefoon gaan” in plaats van “ik ben hopeloos.”',
      'You say, “I notice tension, the thought that I must escape, and my hands reaching for my phone,” instead of “I am hopeless.”',
    ),
    misconception: t(
      'Zelf-als-proces is niet eindeloos analyseren waarom je zo bent; het is actueel en beschrijvend waarnemen.',
      'Self-as-process is not endlessly analysing why you are the way you are; it is current, descriptive noticing.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['self-as-context', 'self-as-content', 'mindfulness'],
    relatedSkillIds: ['beschrijven-benoemen', 'waarnemend-zelf'],
    primaryTheoryLessonId: 'w05-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'triflex',
    frameworks: ['ACT'],
    tier: 'verdieping',
    formalName: t('Triflex', 'Triflex'),
    aliases: [t('open, aanwezig en betrokken', 'open, aware, and engaged')],
    plainExplanation: t(
      'Triflex vat ACT samen in drie bewegingen: openstaan voor ervaring, aanwezig zijn en doen wat belangrijk is.',
      'Triflex summarises ACT in three movements: opening to experience, being present, and doing what matters.',
    ),
    deeperExplanation: t(
      'De zes ACT-processen worden in drie paren gegroepeerd: acceptatie met defusie, huidig moment met zelf-als-context, en waarden met toegewijd handelen. Het is een geheugensteun, geen ander behandelmodel.',
      'The six ACT processes are grouped into three pairs: acceptance with defusion, present-moment contact with self-as-context, and values with committed action. It is a memory aid, not a different treatment model.',
    ),
    example: t(
      'Voor een lastig gesprek maak je ruimte voor spanning, voel je je voeten op de grond en spreek je één eerlijke, respectvolle zin uit.',
      'Before a difficult conversation, you make room for tension, feel your feet on the ground, and say one honest, respectful sentence.',
    ),
    misconception: t(
      'De drie onderdelen zijn geen vaste stappen die altijd in dezelfde volgorde moeten worden uitgevoerd.',
      'The three parts are not fixed steps that must always be completed in the same order.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['acceptance', 'present-moment', 'self-as-context', 'committed-action'],
    relatedSkillIds: ['acceptatie-toestaan', 'hier-en-nu', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w06-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'act-matrix-choice-point',
    frameworks: ['ACT'],
    tier: 'verdieping',
    formalName: t('ACT-matrix en keuzepunt', 'ACT Matrix and Choice Point'),
    aliases: [t('naar-toe en van-weg', 'toward and away'), t('keuzepunt', 'choice point')],
    plainExplanation: t(
      'Deze hulpmiddelen laten zien wanneer gedrag je naar wat belangrijk is brengt en wanneer het vooral van ongemak probeert weg te bewegen.',
      'These tools show when behaviour moves you toward what matters and when it mainly tries to move away from discomfort.',
    ),
    deeperExplanation: t(
      'De matrix ordent innerlijke en zichtbare ervaringen met naar-toe- en van-wegbewegingen. Het keuzepunt zoomt in op een moment waarop je na een aanleiding een automatische of meer waardegerichte stap kunt herkennen.',
      'The Matrix organises inner and observable experiences alongside toward and away moves. The Choice Point focuses on a moment when, after a cue, you can notice an automatic or more values-guided step.',
    ),
    example: t(
      'Na kritiek wil je direct je telefoon uitzetten. Je noteert dat als van-wegreactie en kiest eerst één verhelderende vraag als naar-toestap.',
      'After criticism, you want to switch off your phone immediately. You note that as an away move and first choose one clarifying question as a toward move.',
    ),
    misconception: t(
      'Van-wegbewegingen zijn niet altijd slecht en naar-toebewegingen zijn niet altijd veilig; context en gevolgen blijven belangrijk.',
      'Away moves are not always bad and toward moves are not always safe; context and consequences still matter.',
    ),
    safetyNote: t(
      'Weggaan van werkelijk gevaar is een passende beschermingsactie, ook als het schema die beweging letterlijk als “van weg” tekent.',
      'Moving away from real danger is an appropriate protective action, even if the diagram literally places it in an “away” direction.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['choice-freedom', 'values', 'experiential-avoidance', 'workability'],
    relatedSkillIds: ['waarden-verhelderen', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w08-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'control-agenda',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('controleagenda', 'control agenda'),
    aliases: [t('strijd met de binnenwereld', 'struggle with the inner world'), t('klachten eerst weg-plan', 'symptoms-must-go-first plan')],
    plainExplanation: t(
      'De controleagenda is de regel dat moeilijke gevoelens of gedachten eerst weg moeten voordat je kunt leven.',
      'The control agenda is the rule that difficult feelings or thoughts must disappear before you can live.',
    ),
    deeperExplanation: t(
      'ACT onderzoekt wanneer pogingen om innerlijke ervaringen te beheersen op korte termijn opluchten maar op langere termijn tijd, energie en vrijheid kosten. Het alternatief is niet alle controle opgeven, maar selectiever reageren.',
      'ACT examines when attempts to control private experiences provide short-term relief but cost time, energy, and freedom over the longer term. The alternative is not abandoning all control, but responding more selectively.',
    ),
    example: t(
      'Je wacht met solliciteren tot je helemaal zelfverzekerd bent. Maanden later is de onzekerheid er nog en heb je geen stap gezet.',
      'You wait to apply for a job until you feel completely confident. Months later, the uncertainty remains and you have taken no step.',
    ),
    misconception: t(
      'ACT is niet tegen planning, medicatie, ontspanning of probleemoplossing; het onderzoekt of een controlepoging werkelijk helpt.',
      'ACT is not against planning, medication, relaxation, or problem-solving; it examines whether a control attempt actually helps.',
    ),
    safetyNote: t(
      'Stop of wijzig voorgeschreven behandeling niet om “minder te controleren” zonder overleg met een bevoegde professional.',
      'Do not stop or change prescribed treatment in order to “control less” without consulting a qualified professional.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['experiential-avoidance', 'acceptance', 'workability', 'willingness'],
    relatedSkillIds: ['acceptatie-toestaan', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w03-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'psychological-inflexibility',
    frameworks: ['ACT'],
    tier: 'kern',
    formalName: t('psychologische inflexibiliteit', 'psychological inflexibility'),
    aliases: [t('psychische starheid', 'psychological rigidity'), t('vastzitten in patronen', 'being stuck in patterns')],
    plainExplanation: t(
      'Psychologische inflexibiliteit betekent dat gedachten, gevoelens, regels of gewoontes je keuzeruimte steeds smaller maken.',
      'Psychological inflexibility means that thoughts, feelings, rules or habits repeatedly narrow your room to choose.',
    ),
    deeperExplanation: t(
      'In het ACT-model ontstaat starheid wanneer meerdere processen elkaar versterken: vechten tegen innerlijke ervaring, gedachten letterlijk volgen, vastzitten in tijd of zelfverhalen, onduidelijke waarden en onwerkbaar handelen. Het is een menselijk patroon, geen diagnose of vaste eigenschap.',
      'In the ACT model, rigidity develops when several processes reinforce each other: struggling with inner experience, following thoughts literally, becoming stuck in time or self-stories, unclear values and unworkable action. It is a human pattern, not a diagnosis or fixed trait.',
    ),
    example: t(
      'De regel “ik mag pas gaan als ik zeker ben” houdt je thuis, ook al is contact met vrienden belangrijk voor je.',
      'The rule “I can only go when I feel certain” keeps you at home, even though contact with friends matters to you.',
    ),
    misconception: t(
      'Inflexibiliteit betekent niet dat je zwak, koppig of altijd vastgelopen bent; flexibiliteit verschilt per situatie en kan worden geoefend.',
      'Inflexibility does not mean you are weak, stubborn or always stuck; flexibility varies by situation and can be practised.',
    ),
    sourceIds: modelSources,
    relatedConceptIds: ['psychological-flexibility', 'experiential-avoidance', 'cognitive-fusion', 'self-as-content', 'unclear-imposed-values', 'inaction-impulsivity-rigid-persistence'],
    relatedSkillIds: ['afstand-observeren', 'waarden-verhelderen', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'hexaflex',
    frameworks: ['ACT'],
    tier: 'ondersteunend',
    formalName: t('hexaflex', 'hexaflex'),
    aliases: [t('ACT-zesprocessenmodel', 'ACT six-process model')],
    plainExplanation: t(
      'De hexaflex is een overzicht van zes ACT-processen die samen psychologische flexibiliteit ondersteunen.',
      'The hexaflex is an overview of six ACT processes that together support psychological flexibility.',
    ),
    deeperExplanation: t(
      'Het model ordent contact met het huidige moment, acceptatie, defusie, zelf-als-context, waarden en toegewijd handelen. De onderdelen beïnvloeden elkaar; het is geen test en geen vaste trap die je in één volgorde doorloopt.',
      'The model organises present-moment contact, acceptance, defusion, self-as-context, values and committed action. The parts influence one another; it is not a test or a fixed staircase completed in one order.',
    ),
    example: t(
      'Voor een gesprek merk je spanning op, laat je die even bestaan, ziet je doemgedachte als gedachte en kiest een kleine stap richting eerlijk contact.',
      'Before a conversation, you notice tension, allow it to be present, see your catastrophic thought as a thought and choose a small step towards honest contact.',
    ),
    misconception: t(
      'De zes vakken zijn geen cijfers waarop je kunt slagen of zakken en je hoeft ze niet allemaal tegelijk toe te passen.',
      'The six areas are not scores you can pass or fail, and you do not have to use all of them at once.',
    ),
    sourceIds: sixCoreSources,
    relatedConceptIds: ['psychological-flexibility', 'present-moment', 'acceptance', 'cognitive-defusion', 'self-as-context', 'values', 'committed-action'],
    relatedSkillIds: ['hier-en-nu', 'acceptatie-toestaan', 'defusie-afstand-van-gedachten', 'waarden-verhelderen', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w06-t02',
    reviewStatus: 'source-checked',
  },
];
