import type { PsychologyConcept } from './types';

/**
 * Origineel geschreven begrippen voor de persoonlijke theorieroute.
 * `source-checked` betekent alleen dat de inhoud naast de genoemde publieke bronnen is gelegd;
 * het is geen klinische, professionele of auteursrechtelijke beoordeling.
 */
export const versConcepts: PsychologyConcept[] = [
  {
    id: 'vers',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Vaardigheidstraining Emotieregulatiestoornis (VERS)', en: 'Systems Training for Emotional Predictability and Problem Solving (STEPPS/VERS)' },
    aliases: [{ nl: 'VERS-training', en: 'VERS skills training' }],
    plainExplanation: {
      nl: 'VERS is een vaardigheidstraining voor mensen die emoties vaak snel, sterk of lang voelen. Je leert patronen herkennen en stap voor stap bruikbare vaardigheden inzetten.',
      en: 'VERS is a skills course for people whose emotions often rise quickly, feel intense, or last a long time. You learn to notice patterns and use practical skills step by step.',
    },
    deeperExplanation: {
      nl: 'VERS combineert uitleg over emotionele kwetsbaarheid met oefenen in emotieregulatie, gedrag en het oplossen van problemen. De aanpak ziet moeilijkheden niet als één slecht karaktertrekje, maar als patronen die ontstaan uit aanleg, ervaringen en omstandigheden en die je kunt leren beïnvloeden.',
      en: 'VERS combines education about emotional vulnerability with practice in emotion regulation, behaviour, and problem solving. It does not reduce difficulties to a bad character trait; it treats them as patterns shaped by biology, experience, and circumstances that can be influenced through learning.',
    },
    example: {
      nl: 'Na een kort bericht voel je paniek. In plaats van meteen tien berichten terug te sturen, schat je je pannetje in, beschrijf je wat er gebeurt en kies je één passende vaardigheid.',
      en: 'A short message brings up panic. Instead of sending ten replies at once, you rate your pan, describe what is happening, and choose one fitting skill.',
    },
    misconception: {
      nl: 'VERS is geen test die bepaalt wie je bent en geen garantie dat heftige gevoelens verdwijnen. Het is een oefenraamwerk.',
      en: 'VERS is not a test that decides who you are, and it does not promise that intense feelings will disappear. It is a practice framework.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['stepps', 'emotion-regulation', 'biopsychosocial-vulnerability', 'skill-checklist'],
    relatedSkillIds: ['beschrijven-benoemen', 'gedachten-uitdagen', 'aandacht-verplaatsen', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'stepps',
    frameworks: ['VERS'],
    tier: 'ondersteunend',
    formalName: { nl: 'STEPPS', en: 'STEPPS' },
    aliases: [{ nl: 'Systems Training for Emotional Predictability and Problem Solving', en: 'Systems Training for Emotional Predictability and Problem Solving' }],
    plainExplanation: {
      nl: 'STEPPS is de internationale naam van het programma waarop VERS is gebaseerd.',
      en: 'STEPPS is the international name of the programme on which VERS is based.',
    },
    deeperExplanation: {
      nl: 'De naam verwijst naar training in voorspelbaarder omgaan met emoties en problemen aanpakken. Het programma gebruikt psycho-educatie, concrete vaardigheden en waar mogelijk steun van mensen in de omgeving.',
      en: 'The name refers to training for more predictable responses to emotions and for solving problems. The programme uses psychoeducation, concrete skills, and, where possible, support from people around the participant.',
    },
    example: {
      nl: 'Je gebruikt dezelfde vaste stappen bij verschillende situaties: eerst herkennen, dan reguleren en pas daarna het probleem aanpakken.',
      en: 'You use the same steady steps across different situations: first recognise, then regulate, and only then address the problem.',
    },
    misconception: {
      nl: 'STEPPS en VERS zijn geen twee totaal losstaande behandelvormen; VERS is een Nederlandse uitwerking van hetzelfde vaardigheidsprogramma.',
      en: 'STEPPS and VERS are not two completely separate treatments; VERS is a Dutch adaptation of the same skills programme.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['vers', 'psychoeducation', 'generalisation'],
    relatedSkillIds: ['problemen-aanpakken'],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'psychoeducation',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Psycho-educatie', en: 'Psychoeducation' },
    aliases: [{ nl: 'Uitleg over psychologische patronen', en: 'Learning about psychological patterns' }],
    plainExplanation: {
      nl: 'Psycho-educatie is begrijpelijke uitleg over emoties, gedachten en gedrag, zodat je beter herkent wat er gebeurt en wat je kunt oefenen.',
      en: 'Psychoeducation is clear information about emotions, thoughts, and behaviour, so you can better recognise what is happening and what you can practise.',
    },
    deeperExplanation: {
      nl: 'Kennis kan schaamte en verwarring verminderen, maar wordt pas bruikbaar als je haar verbindt aan je eigen signalen en herhaald oefent. Theorie geeft een kaart; ervaring leert je hoe je die kaart gebruikt.',
      en: 'Knowledge can reduce shame and confusion, but it becomes useful only when you connect it to your own signals and practise repeatedly. Theory provides a map; experience teaches you how to use it.',
    },
    example: {
      nl: 'Je leert dat een actie-impuls onderdeel is van een emotie. Daardoor kun je de impuls herkennen zonder hem meteen uit te voeren.',
      en: 'You learn that an action urge is one part of an emotion. This helps you recognise the urge without acting on it immediately.',
    },
    misconception: {
      nl: 'Iets begrijpen is niet hetzelfde als het al kunnen toepassen. Kennis vervangt oefenen of passende professionele hulp niet.',
      en: 'Understanding something is not the same as being able to apply it. Knowledge does not replace practice or suitable professional support.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro'],
    relatedConceptIds: ['vers', 'emotion-regulation', 'generalisation'],
    relatedSkillIds: [],
    primaryTheoryLessonId: 'w01-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'emotion-regulation',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Emotieregulatie', en: 'Emotion regulation' },
    aliases: [{ nl: 'Omgaan met emoties', en: 'Managing emotions' }],
    plainExplanation: {
      nl: 'Emotieregulatie betekent dat je merkt wat je voelt en bewust kiest hoe je ermee omgaat, zonder te eisen dat de emotie meteen weg moet.',
      en: 'Emotion regulation means noticing what you feel and choosing deliberately how to respond, without demanding that the emotion disappear at once.',
    },
    deeperExplanation: {
      nl: 'Reguleren kan betekenen dat je een emotie verdraagt, de intensiteit beïnvloedt, een impuls uitstelt of passend handelt. Het doel is meer keuzeruimte en minder schade, niet voortdurend kalm zijn.',
      en: 'Regulation can mean allowing an emotion, changing its intensity, delaying an urge, or acting effectively. The aim is more room to choose and less harm, not being calm all the time.',
    },
    example: {
      nl: 'Je bent boos, voelt spanning in je kaken en wacht tien minuten voordat je reageert. Je boosheid mag er zijn, terwijl jij je gedrag kiest.',
      en: 'You are angry, notice tension in your jaw, and wait ten minutes before replying. The anger can be present while you choose your behaviour.',
    },
    misconception: {
      nl: 'Reguleren is niet hetzelfde als onderdrukken, ontkennen of altijd positief denken.',
      en: 'Regulation is not the same as suppressing, denying, or always thinking positively.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotion-regulation-difficulties', 'emotional-episode', 'coping-strategy', 'acceptance'],
    relatedSkillIds: ['beschrijven-benoemen', 'aandacht-verplaatsen', 'adem-vertragen'],
    primaryTheoryLessonId: 'w02-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'emotion-regulation-difficulties',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Moeilijkheden met emotieregulatie', en: 'Emotion regulation difficulties' },
    aliases: [{ nl: 'Emotieregulatieproblemen', en: 'Emotion regulation problems' }],
    plainExplanation: {
      nl: 'Dit betekent dat emoties soms zo snel of sterk oplopen dat bewust kiezen moeilijk wordt.',
      en: 'This means emotions sometimes rise so quickly or strongly that making a deliberate choice becomes difficult.',
    },
    deeperExplanation: {
      nl: 'Moeilijkheden kunnen zitten in signalen herkennen, gevoelens benoemen, impulsen uitstellen, herstellen na spanning of een passende strategie kiezen. Ze verschillen per moment en zijn leerbaar; het is geen complete beschrijving van een persoon.',
      en: 'Difficulties may involve noticing signals, naming feelings, delaying urges, recovering after stress, or selecting a fitting strategy. They vary by moment and can be trained; they are not a complete description of a person.',
    },
    example: {
      nl: 'Je merkt pas dat je spanning hoog is nadat je al hebt geschreeuwd. Een vroeg lichaamssignaal leren herkennen geeft een eerder keuzemoment.',
      en: 'You only notice that your tension is high after you have shouted. Learning an early body signal creates an earlier choice point.',
    },
    misconception: {
      nl: 'Moeite met reguleren betekent niet dat je emoties verkeerd zijn of dat je expres lastig doet.',
      en: 'Difficulty regulating does not mean your emotions are wrong or that you are deliberately being difficult.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotion-regulation', 'biopsychosocial-vulnerability', 'emotional-sensitivity-reactivity-recovery'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'biopsychosocial-vulnerability',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Biopsychosociale kwetsbaarheid', en: 'Biopsychosocial vulnerability' },
    aliases: [{ nl: 'Samenspel van lichaam, psyche en omgeving', en: 'Interaction of body, mind, and environment' }],
    plainExplanation: {
      nl: 'Hoe je op emoties reageert komt voort uit een samenspel van lichamelijke aanleg, ervaringen, gewoonten en je huidige omgeving.',
      en: 'How you respond to emotions grows from an interaction between biology, experience, habits, and your current environment.',
    },
    deeperExplanation: {
      nl: '“Bio” omvat bijvoorbeeld gevoeligheid en slaap; “psycho” omvat leren, aandacht en overtuigingen; “sociaal” omvat relaties, stress en steun. Geen van deze lagen verklaart alles alleen. Verandering in één laag kan het hele patroon beïnvloeden.',
      en: '“Bio” includes factors such as sensitivity and sleep; “psycho” includes learning, attention, and beliefs; “social” includes relationships, stress, and support. No single layer explains everything. Change in one layer can affect the whole pattern.',
    },
    example: {
      nl: 'Na weinig slaap, een eerdere afwijzing en ruzie op het werk raakt een late reactie van een vriend je sterker dan op een rustige dag.',
      en: 'After poor sleep, a past rejection, and conflict at work, a friend replying late affects you more strongly than it would on a calm day.',
    },
    misconception: {
      nl: 'Kwetsbaarheid is geen schuld, zwakte of vaststaand lot. Het model verdeelt geen schuld en doet geen diagnose.',
      en: 'Vulnerability is not blame, weakness, or a fixed fate. The model does not assign blame or make a diagnosis.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotional-sensitivity-reactivity-recovery', 'responsibility-without-blame', 'vulnerability-not-identity'],
    relatedSkillIds: ['slaap-rust', 'eten-regelmaat', 'dagstructuur'],
    primaryTheoryLessonId: 'w01-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'emotional-sensitivity-reactivity-recovery',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Emotionele gevoeligheid, reactiviteit en herstel', en: 'Emotional sensitivity, reactivity, and recovery' },
    aliases: [{ nl: 'Sneller geraakt, sterker reageren, langzamer zakken', en: 'Triggered sooner, reacting more strongly, recovering more slowly' }],
    plainExplanation: {
      nl: 'Emotionele kwetsbaarheid kan drie dingen omvatten: je merkt prikkels snel op, je reactie wordt sterk en het duurt langer voordat je weer op je basisniveau bent.',
      en: 'Emotional vulnerability can involve three things: noticing cues quickly, reacting strongly, and taking longer to return to your usual level.',
    },
    deeperExplanation: {
      nl: 'De drie onderdelen hoeven niet altijd samen op te treden. Iemand kan heel gevoelig zijn maar snel herstellen, of pas laat reageren en daarna lang gespannen blijven. Door ze apart te bekijken ontdek je waar een vaardigheid het meeste helpt.',
      en: 'The three parts do not always occur together. Someone may be highly sensitive but recover quickly, or react later and then remain tense for a long time. Looking at each part separately shows where a skill may help most.',
    },
    example: {
      nl: 'Je hoort een zucht, denkt dat iemand boos is, voelt meteen een golf spanning en blijft er de hele avond mee bezig.',
      en: 'You hear a sigh, think someone is angry, feel an immediate wave of tension, and remain occupied with it all evening.',
    },
    misconception: {
      nl: 'Een gevoelig zenuwstelsel maakt je niet overdreven, kapot of ongeschikt. Het zegt ook niet dat elke interpretatie klopt.',
      en: 'A sensitive nervous system does not make you dramatic, broken, or incapable. It also does not mean every interpretation is correct.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['biopsychosocial-vulnerability', 'trigger', 'pan-model', 'emotion-regulation-difficulties'],
    relatedSkillIds: ['afstand-observeren', 'adem-vertragen'],
    primaryTheoryLessonId: 'w01-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'trigger',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Aanleiding of trigger', en: 'Trigger or prompting event' },
    aliases: [{ nl: 'Uitlokker', en: 'Cue' }],
    plainExplanation: {
      nl: 'Een trigger is iets buiten of in jou waarna een emotionele reactie begint of sterker wordt.',
      en: 'A trigger is something outside or inside you after which an emotional response starts or becomes stronger.',
    },
    deeperExplanation: {
      nl: 'Een trigger kan een gebeurtenis, herinnering, gedachte, lichaamssensatie of verwachting zijn. De aanleiding en de betekenis die je eraan geeft zijn niet hetzelfde; beide kun je apart onderzoeken.',
      en: 'A trigger may be an event, memory, thought, body sensation, or expectation. The cue and the meaning you give it are not the same; each can be examined separately.',
    },
    example: {
      nl: 'De aanleiding is dat iemand niet groet. De gedachte “ze vindt mij waardeloos” is jouw snelle betekenisgeving.',
      en: 'The cue is that someone does not greet you. The thought “she thinks I am worthless” is the quick meaning your mind adds.',
    },
    misconception: {
      nl: 'Een trigger is geen bewijs dat gevaar aanwezig is en geen excuus voor ieder gedrag dat daarna volgt.',
      en: 'A trigger is not proof that danger is present, and it is not an excuse for every behaviour that follows.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotional-episode', 'automatic-thought', 'body-signal', 'schema'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'emotional-episode',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Emotionele episode', en: 'Emotional episode' },
    aliases: [{ nl: 'Emotieketen', en: 'Emotion sequence' }],
    plainExplanation: {
      nl: 'Een emotionele episode is het hele verloop van aanleiding, gedachten, lichaam, gevoel, impuls, gedrag en gevolgen.',
      en: 'An emotional episode is the full sequence of trigger, thoughts, body responses, feeling, urge, behaviour, and consequences.',
    },
    deeperExplanation: {
      nl: 'De onderdelen beïnvloeden elkaar en kunnen in een andere volgorde opvallen. Door de episode als een vertraagde film terug te kijken, vind je meerdere momenten waarop een andere reactie mogelijk was.',
      en: 'The parts influence one another and may become noticeable in a different order. By reviewing the episode like a slowed-down film, you can find several moments where another response was possible.',
    },
    example: {
      nl: 'Geen antwoord → “ik word verlaten” → hartslag omhoog → angst → impuls om te bellen → twintig keer bellen → schaamte en conflict.',
      en: 'No reply → “I am being abandoned” → heart rate rises → fear → urge to call → calling twenty times → shame and conflict.',
    },
    misconception: {
      nl: 'Een episode beschrijven is niet hetzelfde als jezelf veroordelen. Het doel is een patroon zichtbaar maken, niet een schuldige aanwijzen.',
      en: 'Describing an episode is not the same as judging yourself. The aim is to make a pattern visible, not to identify someone to blame.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['trigger', 'body-signal', 'action-urge', 'eis-photo-film'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'body-signal',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Lichaamssignaal', en: 'Body signal' },
    aliases: [{ nl: 'Lichamelijk waarschuwingssignaal', en: 'Physical warning sign' }],
    plainExplanation: {
      nl: 'Een lichaamssignaal is een merkbare verandering, zoals druk op de borst, warmte, trillen of een gespannen kaak.',
      en: 'A body signal is a noticeable change, such as pressure in the chest, warmth, shaking, or a tense jaw.',
    },
    deeperExplanation: {
      nl: 'Lichaamssignalen kunnen vroeg waarschuwen dat spanning oploopt. Ze vertellen dat je zenuwstelsel reageert, maar niet automatisch wat de oorzaak is of of je interpretatie klopt.',
      en: 'Body signals can warn you early that arousal is rising. They show that your nervous system is responding, but they do not automatically reveal the cause or prove that your interpretation is correct.',
    },
    example: {
      nl: 'Je merkt dat je adem hoog zit voordat je beseft dat je bang bent. Dat signaal is een kans om even te vertragen.',
      en: 'You notice shallow breathing before you realise you are afraid. That signal is a chance to slow down.',
    },
    misconception: {
      nl: 'Een lichaamssignaal is geen diagnose. Nieuwe, heftige of onverklaarde lichamelijke klachten horen zo nodig medisch beoordeeld te worden.',
      en: 'A body signal is not a diagnosis. New, severe, or unexplained physical symptoms may need medical assessment.',
    },
    safetyNote: {
      nl: 'Gebruik psychologische uitleg niet om mogelijk acute lichamelijke klachten weg te verklaren. Neem bij twijfel contact op met passende medische hulp.',
      en: 'Do not use a psychological explanation to dismiss possibly urgent physical symptoms. When in doubt, contact suitable medical care.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotional-episode', 'trigger', 'pan-model'],
    relatedSkillIds: ['afstand-observeren', 'adem-vertragen'],
    primaryTheoryLessonId: 'w02-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'action-urge',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Actie-impuls', en: 'Action urge' },
    aliases: [{ nl: 'Neiging om iets te doen', en: 'Urge to act' }],
    plainExplanation: {
      nl: 'Een actie-impuls is de neiging die bij een emotie opkomt, zoals vluchten, aanvallen, vermijden, controleren of toenadering zoeken.',
      en: 'An action urge is the pull that comes with an emotion, such as escaping, attacking, avoiding, checking, or seeking closeness.',
    },
    deeperExplanation: {
      nl: 'Een impuls kan informatie geven over een behoefte, maar is geen opdracht. Tussen merken en doen kan een korte pauze ontstaan waarin je gevolgen, veiligheid en waarden meeweegt.',
      en: 'An urge may provide information about a need, but it is not a command. A brief pause can open between noticing and acting, allowing you to consider consequences, safety, and values.',
    },
    example: {
      nl: 'Je voelt de impuls om een gesprek af te breken. Je benoemt “vluchtneiging”, zet beide voeten neer en vraagt om vijf minuten pauze.',
      en: 'You feel an urge to end the conversation. You name it “urge to escape”, put both feet on the floor, and ask for a five-minute break.',
    },
    misconception: {
      nl: 'Een impuls hebben is niet hetzelfde als hem willen, goedkeuren of uitvoeren.',
      en: 'Having an urge is not the same as wanting, approving, or acting on it.',
    },
    safetyNote: {
      nl: 'Bij een sterke impuls tot zelfbeschadiging of ander direct gevaar: maak veiligheid belangrijker dan de oefening en zoek meteen menselijke hulp.',
      en: 'If there is a strong urge to self-harm or another immediate danger, put safety before the exercise and seek human help now.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotional-episode', 'emotion-regulation', 'safety-plan', 'self-harm-prevention'],
    relatedSkillIds: ['afstand-observeren', 'gronden-54321', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w02-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'responsibility-without-blame',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Verantwoordelijkheid zonder schuld', en: 'Responsibility without blame' },
    aliases: [{ nl: 'Niet jouw schuld, wel jouw volgende stap', en: 'Not your fault, still your next step' }],
    plainExplanation: {
      nl: 'Je hebt je kwetsbaarheid of verleden niet gekozen, maar je kunt wel invloed nemen op wat je nu oefent en doet.',
      en: 'You did not choose your vulnerability or history, but you can influence what you practise and do now.',
    },
    deeperExplanation: {
      nl: 'Schuld vraagt wie slecht is; verantwoordelijkheid vraagt welke stap nu mogelijk is. Deze houding houdt erkenning van onrecht en persoonlijke handelingsruimte tegelijk vast.',
      en: 'Blame asks who is bad; responsibility asks what step is possible now. This stance holds recognition of harm and personal agency at the same time.',
    },
    example: {
      nl: 'Het is niet jouw schuld dat je snel schrikt door eerdere ervaringen. Je kunt wel leren je signalen te herkennen en steun te vragen.',
      en: 'It is not your fault that past experiences make you startle quickly. You can still learn to notice your signals and ask for support.',
    },
    misconception: {
      nl: 'Verantwoordelijkheid nemen betekent niet dat anderen geen verantwoordelijkheid hebben of dat geleden schade onbelangrijk is.',
      en: 'Taking responsibility does not mean others have no responsibility or that harm you experienced does not matter.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['biopsychosocial-vulnerability', 'vulnerability-not-identity', 'committed-action'],
    relatedSkillIds: ['toegewijd-handelen', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w01-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'vulnerability-not-identity',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Kwetsbaarheid is niet je identiteit', en: 'Vulnerability is not identity' },
    aliases: [{ nl: 'Je hebt een patroon, je bent niet het patroon', en: 'You have a pattern; you are not the pattern' }],
    plainExplanation: {
      nl: 'Een kwetsbaarheid of terugkerend patroon is iets wat je ervaart, niet alles wat jij bent.',
      en: 'A vulnerability or recurring pattern is something you experience, not everything you are.',
    },
    deeperExplanation: {
      nl: 'Taal als “ik merk een sterk patroon” laat meer ruimte dan “ik ben nu eenmaal zo”. Je geschiedenis is werkelijk, maar jij bestaat ook uit rollen, relaties, keuzes, waarden en nieuwe ervaringen.',
      en: 'Language such as “I notice a strong pattern” leaves more room than “this is simply who I am”. Your history is real, but you also include roles, relationships, choices, values, and new experiences.',
    },
    example: {
      nl: 'Je verandert “ik ben instabiel” in “mijn emoties wisselen vandaag sterk en ik kan één vaardigheid proberen”.',
      en: 'You change “I am unstable” into “my emotions are shifting strongly today, and I can try one skill”.',
    },
    misconception: {
      nl: 'Afstand nemen van een label betekent niet dat je problemen ontkent of nooit een diagnostische term mag gebruiken.',
      en: 'Taking distance from a label does not mean denying problems or never using a diagnostic term.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps', 'acbs-six-core'],
    relatedConceptIds: ['biopsychosocial-vulnerability', 'responsibility-without-blame', 'self-as-context'],
    relatedSkillIds: ['waarnemend-zelf', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w05-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'pan-model',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Pannetjesmodel', en: 'Pan model' },
    aliases: [{ nl: 'Emotie-intensiteit in pannetjes', en: 'Emotion intensity in pans' }],
    plainExplanation: {
      nl: 'Het pannetjesmodel is een persoonlijke schaal om grof in te schatten hoe hoog je emotionele spanning nu is en welke soort vaardigheid daarbij past.',
      en: 'The pan model is a personal scale for roughly estimating your current emotional intensity and the kind of skill that may fit it.',
    },
    deeperExplanation: {
      nl: 'Een lager pannetje kan ruimte geven voor nadenken of probleemoplossen; bij een hoger pannetje ligt de nadruk eerder op veiligheid, vertragen en het zenuwstelsel helpen zakken. De score is subjectief: jouw “3” hoeft niet hetzelfde te voelen als die van iemand anders.',
      en: 'A lower pan may leave room for reflection or problem solving; at a higher pan the priority is more likely to be safety, slowing down, and helping the nervous system settle. The rating is subjective: your “3” does not have to feel like someone else’s.',
    },
    example: {
      nl: 'Bij pannetje 2 kun je feiten en aannames opschrijven. Bij pannetje 5 kies je eerst afstand van gevaar, gronden en iemand bellen.',
      en: 'At pan 2 you may write down facts and assumptions. At pan 5 you first move away from danger, ground yourself, and call someone.',
    },
    misconception: {
      nl: 'Een pannetje is geen diagnose, objectieve meting, wedstrijd of risicoscore. Een lage score sluit gevaar niet uit en een hoge score bewijst geen gevaar.',
      en: 'A pan is not a diagnosis, objective measurement, competition, or risk score. A low rating does not rule out danger, and a high rating does not prove danger.',
    },
    safetyNote: {
      nl: 'Baseer urgente veiligheidskeuzes niet alleen op een pannetjescijfer. Bij direct gevaar of niet veilig kunnen blijven: zoek meteen menselijke noodhulp.',
      en: 'Do not base urgent safety decisions on a pan number alone. If there is immediate danger or you cannot stay safe, seek human emergency help now.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotional-sensitivity-reactivity-recovery', 'emotion-management-plan', 'safety-plan', 'skill-checklist'],
    relatedSkillIds: ['gronden-54321', 'adem-vertragen', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w11-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'eis',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Emotionele Intensiteit Schaal (EIS)', en: 'Emotional Intensity Scale (EIS)' },
    aliases: [{ nl: 'EIS', en: 'EIS' }],
    plainExplanation: {
      nl: 'De EIS helpt je de intensiteit en het verloop van een emotie op een vaste, persoonlijke manier bij te houden.',
      en: 'The EIS helps you track the intensity and course of an emotion in a consistent, personal way.',
    },
    deeperExplanation: {
      nl: 'Door op meerdere momenten te scoren zie je eerder wanneer spanning stijgt, piekt of zakt. Het gaat vooral om vergelijking met jezelf en om patronen ontdekken, niet om een exact wetenschappelijk meetresultaat.',
      en: 'Rating at several moments can show when arousal begins to rise, peaks, or falls. The main purpose is comparison with yourself and pattern detection, not an exact scientific measurement.',
    },
    example: {
      nl: 'Je noteert spanning 2 vóór een gesprek, 4 tijdens kritiek en 3 na tien minuten wandelen. Zo zie je welk moment en welke stap verschil maakten.',
      en: 'You record intensity 2 before a conversation, 4 during criticism, and 3 after a ten-minute walk. This shows which moment and step made a difference.',
    },
    misconception: {
      nl: 'De EIS is geen diagnose, rapportcijfer of bewijs dat je emotie terecht of onterecht is.',
      en: 'The EIS is not a diagnosis, grade, or proof that your emotion is justified or unjustified.',
    },
    safetyNote: {
      nl: 'Gebruik een EIS-score nooit als enige beoordeling van zelfbeschadigings- of suïciderisico.',
      en: 'Never use an EIS rating as the only assessment of self-harm or suicide risk.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['eis-photo-film', 'pan-model', 'emotional-episode'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'eis-photo-film',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'EIS-foto en EIS-film', en: 'EIS snapshot and EIS film' },
    aliases: [{ nl: 'Momentopname en verloop', en: 'Snapshot and sequence' }],
    plainExplanation: {
      nl: 'Een EIS-foto beschrijft één moment. Een EIS-film volgt hoe de emotie door de tijd verandert.',
      en: 'An EIS snapshot describes one moment. An EIS film follows how the emotion changes over time.',
    },
    deeperExplanation: {
      nl: 'De foto helpt precies waarnemen: wat voel, denk en doe ik nu? De film voegt aanleiding, opeenvolgende reacties, vaardigheden en gevolgen toe. Samen voorkomen ze dat één piekmoment het hele verhaal wordt.',
      en: 'The snapshot supports precise observation: what am I feeling, thinking, and doing now? The film adds the trigger, sequence of responses, skills, and consequences. Together they prevent one peak moment from becoming the whole story.',
    },
    example: {
      nl: 'Foto: “nu boosheid 4, warme wangen, vuisten strak”. Film: “kritiek → boosheid 4 → pauze → wandelen → boosheid 2 → rustig gesprek”.',
      en: 'Snapshot: “anger 4 now, warm cheeks, clenched fists”. Film: “criticism → anger 4 → pause → walk → anger 2 → calm conversation”.',
    },
    misconception: {
      nl: 'Een film is geen lang piekerverhaal. Hij blijft concreet en volgt waarneembare stappen.',
      en: 'A film is not a long rumination story. It stays concrete and follows observable steps.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['eis', 'emotional-episode', 'describe', 'trigger'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'skill-checklist',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Vaardighedenchecklist', en: 'Skills checklist' },
    aliases: [{ nl: 'Vijf VERS-vaardigheden', en: 'Five VERS skills' }],
    plainExplanation: {
      nl: 'De checklist helpt je vijf basisroutes langsgaan: observeren, beschrijven, gedachten uitdagen, aandacht verplaatsen en problemen aanpakken.',
      en: 'The checklist helps you review five basic routes: observe, describe, challenge thoughts, shift attention, and solve problems.',
    },
    deeperExplanation: {
      nl: 'Observeren merkt op zonder direct te handelen. Beschrijven maakt het patroon concreet. Gedachten uitdagen onderzoekt een interpretatie. Aandacht verplaatsen kiest tijdelijk een ander focuspunt. Problemen aanpakken verandert een oplosbare situatie. Niet elke route past op elk moment.',
      en: 'Observe notices without acting immediately. Describe makes the pattern concrete. Thought challenging examines an interpretation. Attention shifting temporarily chooses a different focus. Problem solving changes a solvable situation. Not every route fits every moment.',
    },
    example: {
      nl: 'Je zit op pannetje 4. Eerst observeer en beschrijf je, daarna grond je jezelf. Pas wanneer de spanning zakt onderzoek je de gedachte of het probleem.',
      en: 'You are at pan 4. First you observe and describe, then ground yourself. Only when arousal drops do you examine the thought or problem.',
    },
    misconception: {
      nl: 'De checklist is geen verplicht rijtje dat je altijd helemaal of in exact dezelfde volgorde moet afwerken.',
      en: 'The checklist is not a mandatory list that must always be completed fully or in exactly the same order.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['observe', 'describe', 'thought-challenging', 'attention-shifting', 'problem-solving'],
    relatedSkillIds: ['afstand-observeren', 'beschrijven-benoemen', 'gedachten-uitdagen', 'aandacht-verplaatsen', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w06-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'emotion-management-plan',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Emotiehanteringsplan (EHP)', en: 'Emotion management plan' },
    aliases: [{ nl: 'EHP', en: 'Personal emotion plan' }],
    plainExplanation: {
      nl: 'Een EHP is je persoonlijke, vooraf gemaakte plan met signalen, passende vaardigheden, steun en veiligheidsstappen per intensiteitsniveau.',
      en: 'An emotion management plan is your personal plan made in advance, with signals, fitting skills, support, and safety steps for different intensity levels.',
    },
    deeperExplanation: {
      nl: 'Het plan vertaalt algemene theorie naar jouw herkenbare woorden en haalbare acties. Je maakt het liefst concrete “als-dan”-stappen en werkt het bij op basis van ervaring: wat hielp, wat was te laat en wie kan ondersteunen?',
      en: 'The plan translates general theory into your own recognisable words and feasible actions. It works best with concrete “if-then” steps and regular updates based on experience: what helped, what was too late, and who can support you?',
    },
    example: {
      nl: 'Als ik mijn kaak klem en pannetje 3 bereik, leg ik mijn telefoon weg, adem ik rustig uit en stuur ik één afgesproken bericht aan mijn steunpersoon.',
      en: 'If I clench my jaw and reach pan 3, I put my phone down, slow my exhale, and send one agreed message to my support person.',
    },
    misconception: {
      nl: 'Een EHP is geen garantie en geen vervanging voor een professioneel crisis- of behandelplan wanneer dat nodig is.',
      en: 'An emotion management plan is not a guarantee and does not replace a professional crisis or treatment plan when one is needed.',
    },
    safetyNote: {
      nl: 'Houd urgente contactopties buiten deze app beschikbaar. Bespreek een plan voor ernstig of terugkerend gevaar met een bevoegde hulpverlener.',
      en: 'Keep urgent contact options available outside this app. Discuss a plan for serious or recurring danger with a qualified professional.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['pan-model', 'skill-checklist', 'safety-plan', 'support-network'],
    relatedSkillIds: ['om-hulp-vragen', 'gronden-54321', 'adem-vertragen'],
    primaryTheoryLessonId: 'w11-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'support-network',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Steunnetwerk', en: 'Support network' },
    aliases: [{ nl: 'Steungroep of naastbetrokkenen', en: 'Support team or involved others' }],
    plainExplanation: {
      nl: 'Een steunnetwerk bestaat uit mensen en diensten die op verschillende manieren kunnen helpen bij oefenen, dagelijks leven of veiligheid.',
      en: 'A support network consists of people and services that can help in different ways with practice, daily life, or safety.',
    },
    deeperExplanation: {
      nl: 'Goede steun is concreet afgesproken: wie luistert, wie helpt praktisch, wie oefent mee en wie bel je bij gevaar? De ander hoeft je emotie niet op te lossen en jij mag grenzen stellen aan wat je deelt.',
      en: 'Useful support is agreed concretely: who listens, who helps practically, who practises with you, and whom do you call in danger? The other person does not have to fix your emotion, and you may set limits on what you share.',
    },
    example: {
      nl: 'Met een vriend spreek je af: “Vraag eerst of ik luisteren of meedenken wil; herinner me daarna aan mijn EHP.”',
      en: 'You agree with a friend: “First ask whether I want listening or ideas; then remind me of my emotion plan.”',
    },
    misconception: {
      nl: 'Steun vragen is niet hetzelfde als iemand verantwoordelijk maken voor jouw keuzes of altijd beschikbaarheid eisen.',
      en: 'Asking for support is not the same as making someone responsible for your choices or demanding constant availability.',
    },
    safetyNote: {
      nl: 'Een informeel netwerk vervangt professionele of acute hulp niet. Spreek voor noodsituaties aparte, realistische contactstappen af.',
      en: 'An informal network does not replace professional or emergency help. Agree separate, realistic contact steps for emergencies.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['validation', 'boundaries', 'emotion-management-plan', 'safety-plan'],
    relatedSkillIds: ['om-hulp-vragen', 'grens-aangeven'],
    primaryTheoryLessonId: 'w10-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'generalisation',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Generalisatie', en: 'Generalisation' },
    aliases: [{ nl: 'Vaardigheden meenemen naar het dagelijks leven', en: 'Carrying skills into daily life' }],
    plainExplanation: {
      nl: 'Generalisatie betekent dat je een vaardigheid niet alleen in de les kent, maar ook in verschillende echte situaties leert gebruiken.',
      en: 'Generalisation means learning to use a skill in different real situations, not only knowing it in a lesson.',
    },
    deeperExplanation: {
      nl: 'Een vaardigheid wordt betrouwbaarder door oefenen op rustige én lastige momenten, in meerdere omgevingen en met kleine variaties. Terugkijken op wat werkte helpt je plan steeds persoonlijker en sneller toepasbaar te maken.',
      en: 'A skill becomes more reliable through practice in calm and difficult moments, across different settings, and with small variations. Reviewing what worked makes your plan increasingly personal and easier to use quickly.',
    },
    example: {
      nl: 'Je oefent beschrijven eerst thuis bij lichte irritatie, daarna op werk bij spanning en later tijdens een moeilijk gesprek.',
      en: 'You practise describing first at home with mild irritation, then at work under stress, and later during a difficult conversation.',
    },
    misconception: {
      nl: 'Een terugval of vergeten vaardigheid betekent niet dat de training mislukt is; het laat zien waar meer herhaling of aanpassing nodig is.',
      en: 'A setback or forgotten skill does not mean the training has failed; it shows where more repetition or adaptation is needed.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['skill-checklist', 'emotion-management-plan', 'coping-strategy'],
    relatedSkillIds: ['dagstructuur', 'toegewijd-handelen'],
    primaryTheoryLessonId: 'w12-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'observe',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Observeren', en: 'Observe' },
    aliases: [{ nl: 'Waarnemen', en: 'Notice' }],
    plainExplanation: {
      nl: 'Observeren is bewust opmerken wat er in en om je gebeurt, voordat je het oplost of beoordeelt.',
      en: 'Observing means deliberately noticing what is happening inside and around you before solving or judging it.',
    },
    deeperExplanation: {
      nl: 'Je richt aandacht op gedachten, gevoelens, lichaam en omgeving als gebeurtenissen die veranderen. Een korte, nieuwsgierige waarneming kan het automatische stuk tussen prikkel en reactie zichtbaar maken.',
      en: 'You direct attention to thoughts, feelings, body, and surroundings as changing events. Brief, curious observation can reveal the automatic space between a cue and your response.',
    },
    example: {
      nl: 'Je merkt: “warm gezicht, gedachte dat ik faal, neiging om weg te lopen”. Je hoeft nog niets te besluiten.',
      en: 'You notice: “warm face, thought that I am failing, urge to leave”. You do not have to decide anything yet.',
    },
    misconception: {
      nl: 'Observeren is niet eindeloos naar binnen staren, analyseren of gevaar negeren. Het mag kort zijn en wordt bij onveiligheid gevolgd door handelen.',
      en: 'Observing is not endless inward focus, analysis, or ignoring danger. It can be brief and should be followed by action when safety requires it.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps', 'acbs-six-core'],
    relatedConceptIds: ['describe', 'body-signal', 'present-moment', 'skill-checklist'],
    relatedSkillIds: ['afstand-observeren', 'hier-en-nu'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'describe',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Beschrijven', en: 'Describe' },
    aliases: [{ nl: 'Benoemen zonder oordeel', en: 'Name without judgement' }],
    plainExplanation: {
      nl: 'Beschrijven is in concrete woorden zetten wat je waarneemt: feiten, gedachten, gevoelens, lichaam, impulsen en gedrag.',
      en: 'Describing means putting what you notice into concrete words: facts, thoughts, feelings, body responses, urges, and behaviour.',
    },
    deeperExplanation: {
      nl: 'Precieze taal scheidt waarneming van interpretatie. “Hij keek op zijn telefoon” is een feitelijke beschrijving; “hij vindt mij saai” is een gedachte. Die scheiding maakt een passendere vervolgstap mogelijk.',
      en: 'Precise language separates observation from interpretation. “He looked at his phone” is an observable description; “he thinks I am boring” is a thought. This distinction supports a more fitting next step.',
    },
    example: {
      nl: 'In plaats van “alles gaat mis” schrijf je: “twee afspraken zijn verplaatst; ik voel teleurstelling 3 en spanning in mijn buik”.',
      en: 'Instead of “everything is going wrong”, you write: “two appointments were moved; I feel disappointment 3 and tension in my stomach”.',
    },
    misconception: {
      nl: 'Beschrijven is niet emotieloos praten of doen alsof jouw betekenis er niet toe doet; je labelt de betekenis alleen als gedachte.',
      en: 'Describing is not emotionless speech or pretending your meaning does not matter; you simply label that meaning as a thought.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['observe', 'eis-photo-film', 'automatic-thought', 'emotional-episode'],
    relatedSkillIds: ['beschrijven-benoemen'],
    primaryTheoryLessonId: 'w02-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'thought-challenging',
    frameworks: ['VERS'],
    tier: 'kern',
    formalName: { nl: 'Gedachten uitdagen', en: 'Thought challenging' },
    aliases: [{ nl: 'Een gedachte onderzoeken', en: 'Examine a thought' }],
    plainExplanation: {
      nl: 'Gedachten uitdagen is nagaan welke feiten een gedachte steunen, welke feiten niet passen en welke evenwichtiger uitleg mogelijk is.',
      en: 'Thought challenging means checking which facts support a thought, which facts do not fit, and what more balanced explanation is possible.',
    },
    deeperExplanation: {
      nl: 'Je behandelt een automatische gedachte als een hypothese, niet meteen als waarheid of leugen. Je kijkt naar bewijs, denkfouten, context en bruikbaarheid en formuleert een geloofwaardig alternatief. Dit verschilt van ACT-defusie: uitdagen onderzoekt de inhoud; defusie verandert vooral hoe stevig je eraan vastzit.',
      en: 'You treat an automatic thought as a hypothesis, not instantly as truth or falsehood. You examine evidence, thinking errors, context, and usefulness, then form a believable alternative. This differs from ACT defusion: challenging examines content, while defusion mainly changes how tightly you are caught by it.',
    },
    example: {
      nl: 'Gedachte: “Ze reageert niet, dus ze wil van me af.” Tegenbewijs: ze werkt vandaag en reageerde eerder ook later. Alternatief: “Ik weet nog niet waarom; ik wacht tot vanavond.”',
      en: 'Thought: “She has not replied, so she wants to leave me.” Contrary evidence: she is working today and has replied late before. Alternative: “I do not know why yet; I will wait until tonight.”',
    },
    misconception: {
      nl: 'Uitdagen is geen verplicht positief denken en geen poging om elke pijnlijke gedachte weg te redeneren.',
      en: 'Challenging is not forced positive thinking and not an attempt to reason away every painful thought.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps', 'acbs-six-core'],
    relatedConceptIds: ['automatic-thought', 'thinking-error', 'schema', 'cognitive-defusion'],
    relatedSkillIds: ['gedachten-uitdagen'],
    primaryTheoryLessonId: 'w04-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'attention-shifting',
    frameworks: ['VERS', 'gedeeld'],
    tier: 'kern',
    formalName: { nl: 'Aandacht verplaatsen', en: 'Attention shifting' },
    aliases: [{ nl: 'Bewust een ander focuspunt kiezen', en: 'Deliberately choose another focus' }],
    plainExplanation: {
      nl: 'Aandacht verplaatsen is tijdelijk en bewust je focus richten op iets anders om ruimte te maken of spanning te laten zakken.',
      en: 'Attention shifting means temporarily and deliberately moving your focus to something else to create space or let arousal settle.',
    },
    deeperExplanation: {
      nl: 'De vaardigheid werkt het best met een doel en een terugkeermoment: “twintig minuten wandelen, daarna opnieuw kijken”. Zo is het een flexibele keuze. Vermijding wordt het wanneer je steeds wegblijft van belangrijke gevoelens of situaties en je wereld daardoor kleiner wordt.',
      en: 'The skill works best with a purpose and a return point: “walk for twenty minutes, then review”. This makes it a flexible choice. It becomes avoidance when you repeatedly stay away from important feelings or situations and your world becomes smaller.',
    },
    example: {
      nl: 'Je bent te geëmotioneerd om een mail te schrijven. Je doucht, eet iets en zet een herinnering om de mail om 19.00 uur opnieuw te openen.',
      en: 'You are too emotional to write an email. You shower, eat something, and set a reminder to reopen the email at 7 p.m.',
    },
    misconception: {
      nl: 'Aandacht verplaatsen is niet automatisch wegdrukken. Het verschil zit in bewust kiezen, tijdelijkheid en terugkeren naar wat belangrijk is.',
      en: 'Shifting attention is not automatically suppression. The difference lies in deliberate choice, a temporary pause, and returning to what matters.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps', 'acbs-six-core'],
    relatedConceptIds: ['coping-strategy', 'emotion-regulation', 'experiential-avoidance', 'skill-checklist'],
    relatedSkillIds: ['aandacht-verplaatsen', 'gronden-54321', 'intens-bewegen'],
    primaryTheoryLessonId: 'w06-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'problem-solving',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Problemen aanpakken', en: 'Problem solving' },
    aliases: [{ nl: 'Stapsgewijs probleemoplossen', en: 'Step-by-step problem solving' }],
    plainExplanation: {
      nl: 'Problemen aanpakken is een veranderbare situatie helder maken, opties bedenken, één haalbare stap kiezen en het resultaat evalueren.',
      en: 'Problem solving means defining a changeable situation, generating options, choosing one feasible step, and reviewing the result.',
    },
    deeperExplanation: {
      nl: 'Een bruikbaar proces is: beschrijf alleen het oplosbare deel, kies een klein doel, bedenk meerdere opties zonder direct te oordelen, weeg gevolgen, voer één stap uit en leer van de uitkomst. Eerst reguleren helpt wanneer emotie het denken overspoelt.',
      en: 'A useful process is: define only the solvable part, choose a small goal, generate several options without immediate judgement, weigh consequences, take one step, and learn from the outcome. Regulating first helps when emotion overwhelms thinking.',
    },
    example: {
      nl: '“Mijn leven is chaos” wordt: “er liggen drie ongeopende rekeningen”. Doel: vandaag één rekening openen en een betalingsdatum noteren.',
      en: '“My life is chaos” becomes: “three bills are unopened”. Goal: open one bill today and record its due date.',
    },
    misconception: {
      nl: 'Niet alles is een oplosbaar probleem. Rouw, onzekerheid of een gevoel kan vragen om acceptatie en steun in plaats van een technische oplossing.',
      en: 'Not everything is a solvable problem. Grief, uncertainty, or a feeling may call for acceptance and support rather than a technical solution.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['emotion-regulation', 'life-domains', 'acceptance', 'skill-checklist'],
    relatedSkillIds: ['problemen-aanpakken'],
    primaryTheoryLessonId: 'w09-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'life-domains',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Negen levensgebieden', en: 'Nine life domains' },
    aliases: [{ nl: 'Brede basis voor emotieregulatie', en: 'Broad foundation for emotion regulation' }],
    plainExplanation: {
      nl: 'De levensgebieden helpen je kijken welke dagelijkse basis spanning vergroot of juist herstel ondersteunt.',
      en: 'The life domains help you see which parts of daily life increase strain or support recovery.',
    },
    deeperExplanation: {
      nl: 'De negen gebieden zijn: 1) eten en regelmaat, 2) slaap en rust, 3) bewegen, 4) lichamelijke gezondheid, 5) vrije tijd en plezier, 6) veiligheid en het voorkomen van zelfbeschadiging, 7) werk, opleiding of zinvolle dagactiviteit, 8) financiën en administratie, en 9) relaties. Je hoeft ze niet allemaal tegelijk te verbeteren; één kleine stabiele stap kan al draagkracht geven.',
      en: 'The nine domains are: 1) food and regular meals, 2) sleep and rest, 3) movement, 4) physical health, 5) leisure and enjoyment, 6) safety and prevention of self-harm, 7) work, education, or meaningful daily activity, 8) finances and administration, and 9) relationships. You do not have to improve all of them at once; one small stable step can add capacity.',
    },
    example: {
      nl: 'Je kiest niet “alles op orde”, maar één weekdoel: op vier dagen vóór 10.00 uur ontbijten en de twee lastigste rekeningen samen met iemand openen.',
      en: 'You do not choose “fix everything”, but one weekly goal: eat breakfast before 10 a.m. on four days and open the two hardest bills with someone.',
    },
    misconception: {
      nl: 'De levensgebieden zijn geen morele scorekaart. Ziekte, geld, werk en relaties zijn niet volledig individueel maakbaar.',
      en: 'The life domains are not a moral scorecard. Health, money, work, and relationships are not completely under individual control.',
    },
    safetyNote: {
      nl: 'Zelfbeschadigingspreventie is een veiligheidsgebied, geen gewone leefstijltaak. Bij acuut gevaar is directe menselijke hulp de eerste stap.',
      en: 'Self-harm prevention is a safety domain, not an ordinary lifestyle task. In immediate danger, direct human help comes first.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['problem-solving', 'self-harm-prevention', 'support-network', 'generalisation'],
    relatedSkillIds: ['eten-regelmaat', 'slaap-rust', 'dagstructuur', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w10-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'validation',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Validatie', en: 'Validation' },
    aliases: [{ nl: 'Erkennen wat begrijpelijk is', en: 'Acknowledge what makes sense' }],
    plainExplanation: {
      nl: 'Validatie is laten merken dat een gevoel of reactie begrijpelijk is vanuit iemands situatie, zonder automatisch elk oordeel of gedrag goed te keuren.',
      en: 'Validation means showing that a feeling or response makes sense in someone’s situation, without automatically agreeing with every judgement or behaviour.',
    },
    deeperExplanation: {
      nl: 'Je kunt feiten luisteren, de emotie benoemen en de context erkennen: “na zo’n dag snap ik dat je gespannen bent”. Daarna blijft ruimte voor een grens, correctie of andere keuze. Zelfvalidatie past hetzelfde principe op je eigen ervaring toe.',
      en: 'You can listen to the facts, name the emotion, and acknowledge the context: “after a day like that, I understand why you feel tense”. There is still room afterwards for a boundary, correction, or different choice. Self-validation applies the same principle to your own experience.',
    },
    example: {
      nl: '“Ik snap dat mijn angst na dat bericht opliep. Tegelijk weet ik nog niet wat de afzender bedoelde, dus ik wacht met reageren.”',
      en: '“I understand why my fear rose after that message. At the same time, I do not yet know what the sender meant, so I will wait before responding.”',
    },
    misconception: {
      nl: 'Valideren betekent niet dat een aanname waar is, dat schadelijk gedrag acceptabel is of dat je geen nee mag zeggen.',
      en: 'Validation does not mean an assumption is true, harmful behaviour is acceptable, or you are not allowed to say no.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['boundaries', 'support-network', 'describe', 'responsibility-without-blame'],
    relatedSkillIds: ['beschrijven-benoemen', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w10-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'boundaries',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Grenzen', en: 'Boundaries' },
    aliases: [{ nl: 'Aangeven wat wel en niet past', en: 'State what does and does not work for you' }],
    plainExplanation: {
      nl: 'Een grens is een duidelijke uitspraak of handeling over wat jij doet, toelaat of nodig hebt in een situatie.',
      en: 'A boundary is a clear statement or action about what you will do, allow, or need in a situation.',
    },
    deeperExplanation: {
      nl: 'Een bruikbare grens is specifiek, uitvoerbaar en gericht op jouw gedrag: “als er geschreeuwd wordt, onderbreek ik het gesprek”. Je kunt de ander niet besturen, maar wel aangeven wat je doet wanneer de grens wordt overschreden.',
      en: 'A useful boundary is specific, actionable, and focused on your behaviour: “if shouting starts, I will pause the conversation”. You cannot control the other person, but you can state what you will do if the boundary is crossed.',
    },
    example: {
      nl: '“Ik wil luisteren, maar niet midden in de nacht. Stuur me morgenochtend een bericht; bij direct gevaar bel je de noodhulp.”',
      en: '“I want to listen, but not in the middle of the night. Message me tomorrow morning; in immediate danger, call emergency help.”',
    },
    misconception: {
      nl: 'Een grens is geen straf, dreigement of garantie dat de ander het ermee eens is. Begrenzen en betrokken blijven kunnen samengaan.',
      en: 'A boundary is not a punishment, threat, or guarantee that the other person will agree. Setting limits and remaining caring can coexist.',
    },
    safetyNote: {
      nl: 'Bij dreiging, dwang of geweld kan direct weggaan en deskundige hulp zoeken belangrijker zijn dan een grens netjes uitleggen.',
      en: 'In the presence of threats, coercion, or violence, leaving and seeking expert help may matter more than explaining a boundary neatly.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['validation', 'support-network', 'safety-plan'],
    relatedSkillIds: ['nee-zeggen', 'grens-aangeven', 'om-hulp-vragen'],
    primaryTheoryLessonId: 'w10-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'coping-strategy',
    frameworks: ['VERS', 'gedeeld', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Copingstrategie', en: 'Coping strategy' },
    aliases: [{ nl: 'Manier van omgaan met spanning', en: 'Way of responding to stress' }],
    plainExplanation: {
      nl: 'Een copingstrategie is iets wat je doet om met spanning, emotie of een lastige situatie om te gaan.',
      en: 'A coping strategy is something you do to deal with stress, emotion, or a difficult situation.',
    },
    deeperExplanation: {
      nl: 'Een strategie kan op korte termijn opluchten en op lange termijn kosten hebben, of andersom. De nuttigste vraag is daarom niet alleen “werkt het nu?”, maar ook “wat zijn de gevolgen, past het bij de situatie en houdt het mijn leven ruim?”.',
      en: 'A strategy may bring short-term relief but long-term costs, or the reverse. The most useful question is therefore not only “does it work now?”, but also “what are the consequences, does it fit the situation, and does it keep my life broad?”.',
    },
    example: {
      nl: 'Een avond rust nemen kan herstel ondersteunen. Wekenlang elk contact vermijden kan dezelfde ruststrategie veranderen in een patroon dat eenzaamheid vergroot.',
      en: 'Taking one evening to rest may support recovery. Avoiding all contact for weeks can turn the same rest strategy into a pattern that increases loneliness.',
    },
    misconception: {
      nl: 'Een copingstrategie is niet voor altijd “goed” of “fout”; functie, timing, dosis en gevolgen tellen mee.',
      en: 'A coping strategy is not permanently “good” or “bad”; its function, timing, amount, and consequences matter.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps', 'acbs-six-core'],
    relatedConceptIds: ['emotion-regulation', 'attention-shifting', 'experiential-avoidance', 'workability'],
    relatedSkillIds: ['aandacht-verplaatsen', 'troost-verzorging', 'problemen-aanpakken'],
    primaryTheoryLessonId: 'w03-t01',
    reviewStatus: 'source-checked',
  },
  {
    id: 'automatic-thought',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Automatische gedachte', en: 'Automatic thought' },
    aliases: [{ nl: 'Snelle gedachte', en: 'Quick thought' }],
    plainExplanation: {
      nl: 'Een automatische gedachte is een snelle betekenis of voorspelling die zonder bewuste keuze in je hoofd verschijnt.',
      en: 'An automatic thought is a quick meaning or prediction that appears in your mind without a deliberate choice.',
    },
    deeperExplanation: {
      nl: 'Automatische gedachten voelen vaak als feiten omdat ze snel en vertrouwd zijn. Ze worden beïnvloed door eerdere ervaringen, stemming, aandacht en schema’s. Je kunt ze opmerken, beschrijven, onderzoeken of er met meer afstand naar kijken.',
      en: 'Automatic thoughts often feel like facts because they are fast and familiar. They are shaped by past experience, mood, attention, and schemas. You can notice, describe, examine, or take more distance from them.',
    },
    example: {
      nl: 'Je maakt een fout en meteen verschijnt: “Zie je wel, ik kan niets.” De gedachte kwam automatisch; wat je ermee doet is een volgende stap.',
      en: 'You make a mistake and immediately think: “See, I cannot do anything.” The thought appeared automatically; what you do with it is the next step.',
    },
    misconception: {
      nl: 'Automatisch betekent niet onvermijdelijk waar, onbewust voor altijd of jouw schuld.',
      en: 'Automatic does not mean inevitably true, permanently unconscious, or your fault.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps', 'acbs-six-core'],
    relatedConceptIds: ['thinking-error', 'schema', 'thought-challenging', 'cognitive-fusion'],
    relatedSkillIds: ['beschrijven-benoemen', 'gedachten-uitdagen', 'defusie-afstand-van-gedachten'],
    primaryTheoryLessonId: 'w04-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'thinking-error',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Denkfout', en: 'Thinking error' },
    aliases: [{ nl: 'Cognitieve vertekening', en: 'Cognitive distortion' }],
    plainExplanation: {
      nl: 'Een denkfout is een herkenbare snelkoppeling waardoor je beeld van een situatie eenzijdiger of stelliger kan worden.',
      en: 'A thinking error is a recognisable shortcut that can make your view of a situation more one-sided or certain than the facts allow.',
    },
    deeperExplanation: {
      nl: 'Voorbeelden zijn alles-of-nietsdenken, gedachten lezen, catastroferen, overgeneraliseren en het positieve wegfilteren. Zo’n patroon wijst op een vraag om te onderzoeken; het bewijst niet automatisch dat de conclusie onwaar is.',
      en: 'Examples include all-or-nothing thinking, mind reading, catastrophising, overgeneralising, and filtering out positives. Spotting a pattern signals a question to examine; it does not automatically prove the conclusion false.',
    },
    example: {
      nl: 'Na één afwijzing denk je: “Niemand zal mij ooit willen.” Het woord “niemand” kan wijzen op overgeneraliseren.',
      en: 'After one rejection, you think: “No one will ever want me.” The word “no one” may signal overgeneralising.',
    },
    misconception: {
      nl: '“Denkfout” betekent niet dat jij dom bent, expres verkeerd denkt of dat emoties onterecht zijn.',
      en: '“Thinking error” does not mean you are foolish, thinking wrongly on purpose, or that your emotions are invalid.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['automatic-thought', 'schema', 'thought-challenging'],
    relatedSkillIds: ['gedachten-uitdagen'],
    primaryTheoryLessonId: 'w04-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'schema',
    frameworks: ['VERS', 'algemeen'],
    tier: 'ondersteunend',
    formalName: { nl: 'Schema', en: 'Schema' },
    aliases: [{ nl: 'Diep patroon van verwachtingen', en: 'Deep pattern of expectations' }],
    plainExplanation: {
      nl: 'Een schema is een diep en vertrouwd patroon waarmee je informatie over jezelf, anderen en de wereld snel ordent.',
      en: 'A schema is a deep, familiar pattern that quickly organises information about yourself, other people, and the world.',
    },
    deeperExplanation: {
      nl: 'Schema’s ontstaan door aanleg en herhaalde ervaringen. Ze sturen welke signalen opvallen en welke automatische gedachten geloofwaardig voelen. Een schema kan vroeger beschermend zijn geweest en nu te breed of te star worden toegepast.',
      en: 'Schemas develop through biology and repeated experience. They guide which cues stand out and which automatic thoughts feel believable. A schema may have been protective earlier and now be applied too broadly or rigidly.',
    },
    example: {
      nl: 'Met het schema “mensen verlaten mij” valt een late reactie direct op, terwijl tientallen gewone reacties minder gewicht krijgen.',
      en: 'With the schema “people leave me”, a late reply stands out immediately while dozens of ordinary replies carry less weight.',
    },
    misconception: {
      nl: 'Een schema is geen verborgen absolute waarheid, geen diagnose en geen levenslange identiteit.',
      en: 'A schema is not a hidden absolute truth, a diagnosis, or a lifelong identity.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['automatic-thought', 'thinking-error', 'trigger', 'vulnerability-not-identity'],
    relatedSkillIds: ['gedachten-uitdagen', 'waarnemend-zelf'],
    primaryTheoryLessonId: 'w04-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'safety-plan',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Veiligheidsplan', en: 'Safety plan' },
    aliases: [{ nl: 'Plan voor oplopend of direct gevaar', en: 'Plan for rising or immediate danger' }],
    plainExplanation: {
      nl: 'Een veiligheidsplan legt vooraf vast hoe je signalen herkent, gevaar vermindert en stap voor stap menselijke hulp inschakelt.',
      en: 'A safety plan records in advance how you recognise warning signs, reduce danger, and contact human help step by step.',
    },
    deeperExplanation: {
      nl: 'Een persoonlijk plan kan vroege signalen, interne overbruggingsstappen, veilige plekken, steunpersonen, professionele contacten en manieren om toegang tot gevaarlijke middelen te verkleinen bevatten. Het moet haalbaar, vindbaar en met betrokken mensen afgestemd zijn.',
      en: 'A personal plan may include early warning signs, internal coping steps, safer places, support people, professional contacts, and ways to reduce access to dangerous means. It should be feasible, easy to find, and agreed with involved people.',
    },
    example: {
      nl: 'Bij mijn afgesproken alarmsignalen ga ik niet alleen blijven, leg ik gevaarlijke spullen buiten bereik en bel ik eerst mijn steunpersoon en daarna de afgesproken professionele hulp.',
      en: 'When my agreed warning signs appear, I will not stay alone, I will move dangerous items out of reach, and I will first call my support person and then the agreed professional help.',
    },
    misconception: {
      nl: 'Een plan in een app is geen garantie, risicobeoordeling of vervanging voor direct handelen bij gevaar.',
      en: 'A plan in an app is not a guarantee, risk assessment, or substitute for immediate action in danger.',
    },
    safetyNote: {
      nl: 'Bij acuut gevaar, een concrete intentie of niet veilig kunnen blijven: stop de theorieles, ga naar een veiliger plek en neem direct contact op met lokale noodhulp of een vertrouwde persoon.',
      en: 'In immediate danger, with concrete intent, or if you cannot stay safe: stop the theory lesson, move to a safer place, and contact local emergency help or a trusted person now.',
    },
    sourceIds: ['trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['self-harm-prevention', 'emotion-management-plan', 'support-network', 'pan-model'],
    relatedSkillIds: ['om-hulp-vragen', 'veilige-plek', 'gronden-54321'],
    primaryTheoryLessonId: 'w11-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'self-harm-prevention',
    frameworks: ['VERS', 'algemeen'],
    tier: 'kern',
    formalName: { nl: 'Voorkomen van zelfbeschadiging', en: 'Self-harm prevention' },
    aliases: [{ nl: 'Veiligheid rond zelfbeschadigingsimpulsen', en: 'Safety around urges to self-harm' }],
    plainExplanation: {
      nl: 'Zelfbeschadigingspreventie betekent signalen vroeg herkennen, tijd winnen, gevaar verkleinen en passende menselijke steun inzetten.',
      en: 'Self-harm prevention means noticing warning signs early, creating time, reducing danger, and involving suitable human support.',
    },
    deeperExplanation: {
      nl: 'Een impuls kan opkomen als poging om ondraaglijke spanning te veranderen. De functie begrijpen helpt alternatieven zoeken, maar veiligheid blijft eerst: afstand van middelen, niet alleen blijven wanneer dat onveilig is en vooraf afgesproken hulp inschakelen.',
      en: 'An urge may arise as an attempt to change unbearable distress. Understanding its function can help identify alternatives, but safety comes first: create distance from means, do not stay alone when that is unsafe, and use agreed sources of help.',
    },
    example: {
      nl: 'Je merkt je waarschuwingssignaal en volgt niet alleen een kalmerende oefening: je verlaat de onveilige ruimte, geeft middelen af en belt de afgesproken persoon.',
      en: 'You notice your warning sign and do more than a calming exercise: you leave the unsafe space, hand over means, and call the agreed person.',
    },
    misconception: {
      nl: 'Zelfbeschadiging is niet simpelweg aandacht zoeken, maar de app kan niet vaststellen hoe hoog het risico is of je veilig houden.',
      en: 'Self-harm is not simply attention seeking, but the app cannot determine your level of risk or keep you safe.',
    },
    safetyNote: {
      nl: 'Bij direct gevaar of als je jezelf mogelijk iets aandoet: gebruik nu lokale noodhulp, je professionele crisiscontact of een vertrouwde persoon en blijf niet alleen als dat onveilig is.',
      en: 'If there is immediate danger or you may harm yourself: contact local emergency help, your professional crisis contact, or a trusted person now, and do not stay alone if that is unsafe.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro', 'uiowa-stepps'],
    relatedConceptIds: ['safety-plan', 'action-urge', 'emotion-management-plan', 'life-domains'],
    relatedSkillIds: ['om-hulp-vragen', 'veilige-plek', 'gronden-54321'],
    primaryTheoryLessonId: 'w11-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'vers-two',
    frameworks: ['VERS'],
    tier: 'verdieping',
    formalName: { nl: 'VERS II', en: 'VERS II' },
    aliases: [{ nl: 'Verdieping na VERS I', en: 'Follow-on learning after VERS I' }],
    plainExplanation: {
      nl: 'VERS II is een verdiepende vervolgvariant binnen het VERS-aanbod; deze app geeft alleen een begripsmatige verwijzing en bootst het programma niet na.',
      en: 'VERS II is a more advanced follow-on within the VERS programme; this app only provides a conceptual reference and does not reproduce the programme.',
    },
    deeperExplanation: {
      nl: 'Een vervolgtraining bouwt voort op basiskennis en herhaald toepassen van vaardigheden. Welke inhoud, vorm en toelating gelden hoort bij de actuele aanbieder en een passende professionele beoordeling, niet bij deze persoonlijke app.',
      en: 'A follow-on course builds on basic knowledge and repeated application of skills. Its current content, format, and suitability belong to the provider and an appropriate professional assessment, not to this personal app.',
    },
    example: {
      nl: 'In de begrippenbibliotheek kom je “VERS II” tegen. Je leest wat de term globaal betekent, maar krijgt hier geen nagebouwde VERS-II-handleiding.',
      en: 'You encounter “VERS II” in the glossary. You learn what the term broadly means, but you do not receive a recreated VERS II manual here.',
    },
    misconception: {
      nl: 'Het afronden van deze app betekent niet dat je een officiële VERS-training of VERS II hebt gevolgd.',
      en: 'Completing this app does not mean you have completed an official VERS course or VERS II.',
    },
    sourceIds: ['trimbos-vers-training', 'trimbos-vers-intro'],
    relatedConceptIds: ['vers', 'stepps', 'generalisation'],
    relatedSkillIds: [],
    primaryTheoryLessonId: 'w12-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'thought-record',
    frameworks: ['VERS', 'algemeen'],
    tier: 'ondersteunend',
    formalName: { nl: 'G-schema', en: 'thought record' },
    aliases: [
      { nl: '5G-schema', en: '5G thought record' },
      { nl: 'gedachtedagboek', en: 'thought diary' },
    ],
    plainExplanation: {
      nl: 'Een G-schema zet een gebeurtenis, gedachten, gevoelens, gedrag en gevolgen stap voor stap naast elkaar.',
      en: 'A thought record places an event, thoughts, feelings, behaviour and consequences alongside one another step by step.',
    },
    deeperExplanation: {
      nl: 'Door de onderdelen te scheiden wordt zichtbaar welke automatische gedachte meespeelde en welke feiten ervoor en ertegen zijn. Daarna kun je een eerlijker alternatief formuleren en opnieuw kijken wat je voelt of wilt doen.',
      en: 'Separating the parts can reveal the automatic thought involved and the evidence for and against it. You can then form a fairer alternative and look again at what you feel or want to do.',
    },
    example: {
      nl: 'Gebeurtenis: iemand antwoordt kort. Gedachte: “ze is boos op mij”. Gevoel: angst. Gedrag: terugtrekken. Onderzoek laat ook andere verklaringen zien.',
      en: 'Event: someone replies briefly. Thought: “she is angry with me”. Feeling: anxiety. Behaviour: withdrawing. Examination reveals other possible explanations too.',
    },
    misconception: {
      nl: 'Een schema bewijst niet dat een gedachte fout is en is niet bedoeld om echte problemen, gevaar of grenzen weg te redeneren.',
      en: 'A thought record does not prove that a thought is wrong and is not meant to reason away real problems, danger or boundaries.',
    },
    safetyNote: {
      nl: 'Bij pan 4 of 5 kies je meestal eerst veiligheid, regulatie of steun en vul je een uitgebreid schema later in.',
      en: 'At level 4 or 5, usually choose safety, regulation or support first and complete a detailed record later.',
    },
    sourceIds: ['trimbos-vers-intro', 'cci-thinking-feeling'],
    relatedConceptIds: ['automatic-thought', 'thinking-error', 'thought-challenging', 'schema'],
    relatedSkillIds: ['gedachten-uitdagen'],
    primaryTheoryLessonId: 'w04-t02',
    reviewStatus: 'source-checked',
  },
  {
    id: 'worry',
    frameworks: ['VERS', 'algemeen'],
    tier: 'ondersteunend',
    formalName: { nl: 'piekeren', en: 'worry' },
    aliases: [
      { nl: 'maalgedachten', en: 'repetitive worry' },
      { nl: 'blijven malen', en: 'ruminating on possible problems' },
    ],
    plainExplanation: {
      nl: 'Piekeren is herhaald denken over mogelijke problemen zonder dat het denken vanzelf tot een concrete volgende stap leidt.',
      en: 'Worry is repeated thinking about possible problems without the thinking naturally leading to a concrete next step.',
    },
    deeperExplanation: {
      nl: 'Piekeren kan voelen als voorbereiden, maar blijft vaak breed, herhalend en gericht op onzekerheid. Probleemoplossen maakt het onderwerp juist concreet: wat is veranderbaar, welke opties zijn er en wat is de eerstvolgende actie?',
      en: 'Worry can feel like preparation, but it often remains broad, repetitive and focused on uncertainty. Problem solving makes the subject concrete: what can be changed, what options exist and what is the next action?',
    },
    example: {
      nl: '“Wat als alles misgaat?” blijft een uur rondgaan. Je stopt en vraagt: welk deel kan ik vandaag beïnvloeden en welke stap duurt tien minuten?',
      en: '“What if everything goes wrong?” circles for an hour. You pause and ask: which part can I influence today, and what step takes ten minutes?',
    },
    misconception: {
      nl: 'Piekeren betekent niet dat je zorgen onbelangrijk of onwaar zijn; het beschrijft de herhalende manier van denken, niet de waarde van het onderwerp.',
      en: 'Worry does not mean your concerns are unimportant or untrue; it describes the repetitive way of thinking, not the value of the subject.',
    },
    sourceIds: ['trimbos-vers-intro', 'cci-thinking-feeling'],
    relatedConceptIds: ['problem-solving', 'automatic-thought', 'past-future-dominance', 'attention-shifting'],
    relatedSkillIds: ['problemen-aanpakken', 'aandacht-verplaatsen'],
    primaryTheoryLessonId: 'w09-t01',
    reviewStatus: 'source-checked',
  },
];
